// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AddDeltaHandler(ReducerEventContext ctx, ulong programId, string rankTag, string triggerCode, string triggerRegion, string triggerState, string targetCode, string targetRegion, SpacetimeDB.Types.PropChange change, string tau, System.Collections.Generic.List<string> depends, string? status, string? cascadeName, string? tensorExpr);
        public event AddDeltaHandler? OnAddDelta;

        public void AddDelta(ulong programId, string rankTag, string triggerCode, string triggerRegion, string triggerState, string targetCode, string targetRegion, SpacetimeDB.Types.PropChange change, string tau, System.Collections.Generic.List<string> depends, string? status, string? cascadeName, string? tensorExpr)
        {
            conn.InternalCallReducer(new Reducer.AddDelta(programId, rankTag, triggerCode, triggerRegion, triggerState, targetCode, targetRegion, change, tau, depends, status, cascadeName, tensorExpr));
        }

        public bool InvokeAddDelta(ReducerEventContext ctx, Reducer.AddDelta args)
        {
            if (OnAddDelta == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAddDelta(
                ctx,
                args.ProgramId,
                args.RankTag,
                args.TriggerCode,
                args.TriggerRegion,
                args.TriggerState,
                args.TargetCode,
                args.TargetRegion,
                args.Change,
                args.Tau,
                args.Depends,
                args.Status,
                args.CascadeName,
                args.TensorExpr
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AddDelta : Reducer, IReducerArgs
        {
            [DataMember(Name = "program_id")]
            public ulong ProgramId;
            [DataMember(Name = "rank_tag")]
            public string RankTag;
            [DataMember(Name = "trigger_code")]
            public string TriggerCode;
            [DataMember(Name = "trigger_region")]
            public string TriggerRegion;
            [DataMember(Name = "trigger_state")]
            public string TriggerState;
            [DataMember(Name = "target_code")]
            public string TargetCode;
            [DataMember(Name = "target_region")]
            public string TargetRegion;
            [DataMember(Name = "change")]
            public PropChange Change;
            [DataMember(Name = "tau")]
            public string Tau;
            [DataMember(Name = "depends")]
            public System.Collections.Generic.List<string> Depends;
            [DataMember(Name = "status")]
            public string? Status;
            [DataMember(Name = "cascade_name")]
            public string? CascadeName;
            [DataMember(Name = "tensor_expr")]
            public string? TensorExpr;

            public AddDelta(
                ulong ProgramId,
                string RankTag,
                string TriggerCode,
                string TriggerRegion,
                string TriggerState,
                string TargetCode,
                string TargetRegion,
                PropChange Change,
                string Tau,
                System.Collections.Generic.List<string> Depends,
                string? Status,
                string? CascadeName,
                string? TensorExpr
            )
            {
                this.ProgramId = ProgramId;
                this.RankTag = RankTag;
                this.TriggerCode = TriggerCode;
                this.TriggerRegion = TriggerRegion;
                this.TriggerState = TriggerState;
                this.TargetCode = TargetCode;
                this.TargetRegion = TargetRegion;
                this.Change = Change;
                this.Tau = Tau;
                this.Depends = Depends;
                this.Status = Status;
                this.CascadeName = CascadeName;
                this.TensorExpr = TensorExpr;
            }

            public AddDelta()
            {
                this.RankTag = "";
                this.TriggerCode = "";
                this.TriggerRegion = "";
                this.TriggerState = "";
                this.TargetCode = "";
                this.TargetRegion = "";
                this.Change = new();
                this.Tau = "";
                this.Depends = new();
            }

            string IReducerArgs.ReducerName => "add_delta";
        }
    }
}
