// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DiffSnapshotsHandler(ReducerEventContext ctx, ulong programId, ulong snapAId, ulong snapBId);
        public event DiffSnapshotsHandler? OnDiffSnapshots;

        public void DiffSnapshots(ulong programId, ulong snapAId, ulong snapBId)
        {
            conn.InternalCallReducer(new Reducer.DiffSnapshots(programId, snapAId, snapBId));
        }

        public bool InvokeDiffSnapshots(ReducerEventContext ctx, Reducer.DiffSnapshots args)
        {
            if (OnDiffSnapshots == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDiffSnapshots(
                ctx,
                args.ProgramId,
                args.SnapAId,
                args.SnapBId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DiffSnapshots : Reducer, IReducerArgs
        {
            [DataMember(Name = "program_id")]
            public ulong ProgramId;
            [DataMember(Name = "snap_a_id")]
            public ulong SnapAId;
            [DataMember(Name = "snap_b_id")]
            public ulong SnapBId;

            public DiffSnapshots(
                ulong ProgramId,
                ulong SnapAId,
                ulong SnapBId
            )
            {
                this.ProgramId = ProgramId;
                this.SnapAId = SnapAId;
                this.SnapBId = SnapBId;
            }

            public DiffSnapshots()
            {
            }

            string IReducerArgs.ReducerName => "diff_snapshots";
        }
    }
}
