// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void QuerySimRunsHandler(ReducerEventContext ctx, ulong programId);
        public event QuerySimRunsHandler? OnQuerySimRuns;

        public void QuerySimRuns(ulong programId)
        {
            conn.InternalCallReducer(new Reducer.QuerySimRuns(programId));
        }

        public bool InvokeQuerySimRuns(ReducerEventContext ctx, Reducer.QuerySimRuns args)
        {
            if (OnQuerySimRuns == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnQuerySimRuns(
                ctx,
                args.ProgramId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class QuerySimRuns : Reducer, IReducerArgs
        {
            [DataMember(Name = "program_id")]
            public ulong ProgramId;

            public QuerySimRuns(ulong ProgramId)
            {
                this.ProgramId = ProgramId;
            }

            public QuerySimRuns()
            {
            }

            string IReducerArgs.ReducerName => "query_sim_runs";
        }
    }
}
