// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class DeltaOpHandle : RemoteTableHandle<EventContext, DeltaOp>
        {
            protected override string RemoteTableName => "delta_op";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(DeltaOp row) => row.Id;

                public IdUniqueIndex(DeltaOpHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class ByProgramIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(DeltaOp row) => row.ProgramId;

                public ByProgramIndex(DeltaOpHandle table) : base(table) { }
            }

            public readonly ByProgramIndex ByProgram;

            public sealed class ByRankIndex : BTreeIndexBase<(ulong ProgramId, string RankTag)>
            {
                protected override (ulong ProgramId, string RankTag) GetKey(DeltaOp row) => (row.ProgramId, row.RankTag);

                public ByRankIndex(DeltaOpHandle table) : base(table) { }
            }

            public readonly ByRankIndex ByRank;

            internal DeltaOpHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                ByProgram = new(this);
                ByRank = new(this);
            }

            protected override object GetPrimaryKey(DeltaOp row) => row.Id;
        }

        public readonly DeltaOpHandle DeltaOp;
    }

    public sealed class DeltaOpCols
    {
        public global::SpacetimeDB.Col<DeltaOp, ulong> Id { get; }
        public global::SpacetimeDB.Col<DeltaOp, ulong> ProgramId { get; }
        public global::SpacetimeDB.Col<DeltaOp, string> RankTag { get; }
        public global::SpacetimeDB.Col<DeltaOp, string> TriggerCode { get; }
        public global::SpacetimeDB.Col<DeltaOp, string> TriggerRegion { get; }
        public global::SpacetimeDB.Col<DeltaOp, string> TriggerState { get; }
        public global::SpacetimeDB.Col<DeltaOp, string> TargetCode { get; }
        public global::SpacetimeDB.Col<DeltaOp, string> TargetRegion { get; }
        public global::SpacetimeDB.Col<DeltaOp, PropChange> Change { get; }
        public global::SpacetimeDB.Col<DeltaOp, string> Tau { get; }
        public global::SpacetimeDB.Col<DeltaOp, System.Collections.Generic.List<string>> Depends { get; }
        public global::SpacetimeDB.NullableCol<DeltaOp, string> Status { get; }
        public global::SpacetimeDB.NullableCol<DeltaOp, string> CascadeName { get; }
        public global::SpacetimeDB.NullableCol<DeltaOp, string> TensorExpr { get; }

        public DeltaOpCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<DeltaOp, ulong>(tableName, "id");
            ProgramId = new global::SpacetimeDB.Col<DeltaOp, ulong>(tableName, "program_id");
            RankTag = new global::SpacetimeDB.Col<DeltaOp, string>(tableName, "rank_tag");
            TriggerCode = new global::SpacetimeDB.Col<DeltaOp, string>(tableName, "trigger_code");
            TriggerRegion = new global::SpacetimeDB.Col<DeltaOp, string>(tableName, "trigger_region");
            TriggerState = new global::SpacetimeDB.Col<DeltaOp, string>(tableName, "trigger_state");
            TargetCode = new global::SpacetimeDB.Col<DeltaOp, string>(tableName, "target_code");
            TargetRegion = new global::SpacetimeDB.Col<DeltaOp, string>(tableName, "target_region");
            Change = new global::SpacetimeDB.Col<DeltaOp, PropChange>(tableName, "change");
            Tau = new global::SpacetimeDB.Col<DeltaOp, string>(tableName, "tau");
            Depends = new global::SpacetimeDB.Col<DeltaOp, System.Collections.Generic.List<string>>(tableName, "depends");
            Status = new global::SpacetimeDB.NullableCol<DeltaOp, string>(tableName, "status");
            CascadeName = new global::SpacetimeDB.NullableCol<DeltaOp, string>(tableName, "cascade_name");
            TensorExpr = new global::SpacetimeDB.NullableCol<DeltaOp, string>(tableName, "tensor_expr");
        }
    }

    public sealed class DeltaOpIxCols
    {
        public global::SpacetimeDB.IxCol<DeltaOp, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<DeltaOp, ulong> ProgramId { get; }
        public global::SpacetimeDB.IxCol<DeltaOp, string> RankTag { get; }

        public DeltaOpIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<DeltaOp, ulong>(tableName, "id");
            ProgramId = new global::SpacetimeDB.IxCol<DeltaOp, ulong>(tableName, "program_id");
            RankTag = new global::SpacetimeDB.IxCol<DeltaOp, string>(tableName, "rank_tag");
        }
    }
}
