// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ProgramHandle : RemoteTableHandle<EventContext, Program>
        {
            protected override string RemoteTableName => "program";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(Program row) => row.Id;

                public IdUniqueIndex(ProgramHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class ByPatientIndex : BTreeIndexBase<string>
            {
                protected override string GetKey(Program row) => row.PatientId;

                public ByPatientIndex(ProgramHandle table) : base(table) { }
            }

            public readonly ByPatientIndex ByPatient;

            internal ProgramHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                ByPatient = new(this);
            }

            protected override object GetPrimaryKey(Program row) => row.Id;
        }

        public readonly ProgramHandle Program;
    }

    public sealed class ProgramCols
    {
        public global::SpacetimeDB.Col<Program, ulong> Id { get; }
        public global::SpacetimeDB.Col<Program, string> PatientId { get; }
        public global::SpacetimeDB.Col<Program, string> Name { get; }
        public global::SpacetimeDB.NullableCol<Program, string> Phase { get; }
        public global::SpacetimeDB.Col<Program, System.Collections.Generic.List<string>> Domains { get; }
        public global::SpacetimeDB.Col<Program, uint> Tick { get; }
        public global::SpacetimeDB.NullableCol<Program, string> RawBase { get; }
        public global::SpacetimeDB.NullableCol<Program, string> RawPlasticity { get; }
        public global::SpacetimeDB.NullableCol<Program, string> RawMeta { get; }
        public global::SpacetimeDB.NullableCol<Program, string> RawConvergence { get; }
        public global::SpacetimeDB.Col<Program, SpacetimeDB.Timestamp> CreatedAt { get; }

        public ProgramCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<Program, ulong>(tableName, "id");
            PatientId = new global::SpacetimeDB.Col<Program, string>(tableName, "patient_id");
            Name = new global::SpacetimeDB.Col<Program, string>(tableName, "name");
            Phase = new global::SpacetimeDB.NullableCol<Program, string>(tableName, "phase");
            Domains = new global::SpacetimeDB.Col<Program, System.Collections.Generic.List<string>>(tableName, "domains");
            Tick = new global::SpacetimeDB.Col<Program, uint>(tableName, "tick");
            RawBase = new global::SpacetimeDB.NullableCol<Program, string>(tableName, "raw_base");
            RawPlasticity = new global::SpacetimeDB.NullableCol<Program, string>(tableName, "raw_plasticity");
            RawMeta = new global::SpacetimeDB.NullableCol<Program, string>(tableName, "raw_meta");
            RawConvergence = new global::SpacetimeDB.NullableCol<Program, string>(tableName, "raw_convergence");
            CreatedAt = new global::SpacetimeDB.Col<Program, SpacetimeDB.Timestamp>(tableName, "created_at");
        }
    }

    public sealed class ProgramIxCols
    {
        public global::SpacetimeDB.IxCol<Program, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<Program, string> PatientId { get; }

        public ProgramIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<Program, ulong>(tableName, "id");
            PatientId = new global::SpacetimeDB.IxCol<Program, string>(tableName, "patient_id");
        }
    }
}
