// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class SimRunHandle : RemoteTableHandle<EventContext, SimRun>
        {
            protected override string RemoteTableName => "sim_run";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(SimRun row) => row.Id;

                public IdUniqueIndex(SimRunHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class ByProgramIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(SimRun row) => row.ProgramId;

                public ByProgramIndex(SimRunHandle table) : base(table) { }
            }

            public readonly ByProgramIndex ByProgram;

            internal SimRunHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                ByProgram = new(this);
            }

            protected override object GetPrimaryKey(SimRun row) => row.Id;
        }

        public readonly SimRunHandle SimRun;
    }

    public sealed class SimRunCols
    {
        public global::SpacetimeDB.Col<SimRun, ulong> Id { get; }
        public global::SpacetimeDB.Col<SimRun, ulong> ProgramId { get; }
        public global::SpacetimeDB.Col<SimRun, uint> MaxTicks { get; }
        public global::SpacetimeDB.Col<SimRun, System.Collections.Generic.List<Perturbation>> Perturbations { get; }
        public global::SpacetimeDB.Col<SimRun, string> Status { get; }
        public global::SpacetimeDB.Col<SimRun, uint> FinalTick { get; }
        public global::SpacetimeDB.Col<SimRun, SpacetimeDB.Timestamp> StartedAt { get; }

        public SimRunCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<SimRun, ulong>(tableName, "id");
            ProgramId = new global::SpacetimeDB.Col<SimRun, ulong>(tableName, "program_id");
            MaxTicks = new global::SpacetimeDB.Col<SimRun, uint>(tableName, "max_ticks");
            Perturbations = new global::SpacetimeDB.Col<SimRun, System.Collections.Generic.List<Perturbation>>(tableName, "perturbations");
            Status = new global::SpacetimeDB.Col<SimRun, string>(tableName, "status");
            FinalTick = new global::SpacetimeDB.Col<SimRun, uint>(tableName, "final_tick");
            StartedAt = new global::SpacetimeDB.Col<SimRun, SpacetimeDB.Timestamp>(tableName, "started_at");
        }
    }

    public sealed class SimRunIxCols
    {
        public global::SpacetimeDB.IxCol<SimRun, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<SimRun, ulong> ProgramId { get; }

        public SimRunIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<SimRun, ulong>(tableName, "id");
            ProgramId = new global::SpacetimeDB.IxCol<SimRun, ulong>(tableName, "program_id");
        }
    }
}
