// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class SnapshotHandle : RemoteTableHandle<EventContext, Snapshot>
        {
            protected override string RemoteTableName => "snapshot";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(Snapshot row) => row.Id;

                public IdUniqueIndex(SnapshotHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class ByProgramIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(Snapshot row) => row.ProgramId;

                public ByProgramIndex(SnapshotHandle table) : base(table) { }
            }

            public readonly ByProgramIndex ByProgram;

            internal SnapshotHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                ByProgram = new(this);
            }

            protected override object GetPrimaryKey(Snapshot row) => row.Id;
        }

        public readonly SnapshotHandle Snapshot;
    }

    public sealed class SnapshotCols
    {
        public global::SpacetimeDB.Col<Snapshot, ulong> Id { get; }
        public global::SpacetimeDB.Col<Snapshot, ulong> ProgramId { get; }
        public global::SpacetimeDB.Col<Snapshot, uint> Tick { get; }
        public global::SpacetimeDB.NullableCol<Snapshot, string> Label { get; }
        public global::SpacetimeDB.Col<Snapshot, SpacetimeDB.Timestamp> CreatedAt { get; }

        public SnapshotCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<Snapshot, ulong>(tableName, "id");
            ProgramId = new global::SpacetimeDB.Col<Snapshot, ulong>(tableName, "program_id");
            Tick = new global::SpacetimeDB.Col<Snapshot, uint>(tableName, "tick");
            Label = new global::SpacetimeDB.NullableCol<Snapshot, string>(tableName, "label");
            CreatedAt = new global::SpacetimeDB.Col<Snapshot, SpacetimeDB.Timestamp>(tableName, "created_at");
        }
    }

    public sealed class SnapshotIxCols
    {
        public global::SpacetimeDB.IxCol<Snapshot, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<Snapshot, ulong> ProgramId { get; }

        public SnapshotIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<Snapshot, ulong>(tableName, "id");
            ProgramId = new global::SpacetimeDB.IxCol<Snapshot, ulong>(tableName, "program_id");
        }
    }
}
