// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class TensorHandle : RemoteTableHandle<EventContext, Tensor>
        {
            protected override string RemoteTableName => "tensor";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(Tensor row) => row.Id;

                public IdUniqueIndex(TensorHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class ByProgramIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(Tensor row) => row.ProgramId;

                public ByProgramIndex(TensorHandle table) : base(table) { }
            }

            public readonly ByProgramIndex ByProgram;

            internal TensorHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                ByProgram = new(this);
            }

            protected override object GetPrimaryKey(Tensor row) => row.Id;
        }

        public readonly TensorHandle Tensor;
    }

    public sealed class TensorCols
    {
        public global::SpacetimeDB.Col<Tensor, ulong> Id { get; }
        public global::SpacetimeDB.Col<Tensor, ulong> ProgramId { get; }
        public global::SpacetimeDB.Col<Tensor, System.Collections.Generic.List<TensorCond>> Conditions { get; }
        public global::SpacetimeDB.Col<Tensor, string> Logic { get; }
        public global::SpacetimeDB.Col<Tensor, TensorEffect> Effect { get; }
        public global::SpacetimeDB.NullableCol<Tensor, string> Label { get; }

        public TensorCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<Tensor, ulong>(tableName, "id");
            ProgramId = new global::SpacetimeDB.Col<Tensor, ulong>(tableName, "program_id");
            Conditions = new global::SpacetimeDB.Col<Tensor, System.Collections.Generic.List<TensorCond>>(tableName, "conditions");
            Logic = new global::SpacetimeDB.Col<Tensor, string>(tableName, "logic");
            Effect = new global::SpacetimeDB.Col<Tensor, TensorEffect>(tableName, "effect");
            Label = new global::SpacetimeDB.NullableCol<Tensor, string>(tableName, "label");
        }
    }

    public sealed class TensorIxCols
    {
        public global::SpacetimeDB.IxCol<Tensor, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<Tensor, ulong> ProgramId { get; }

        public TensorIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<Tensor, ulong>(tableName, "id");
            ProgramId = new global::SpacetimeDB.IxCol<Tensor, ulong>(tableName, "program_id");
        }
    }
}
