// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ConvHandle : RemoteTableHandle<EventContext, Conv>
        {
            protected override string RemoteTableName => "conv";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(Conv row) => row.Id;

                public IdUniqueIndex(ConvHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class ByProgramIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(Conv row) => row.ProgramId;

                public ByProgramIndex(ConvHandle table) : base(table) { }
            }

            public readonly ByProgramIndex ByProgram;

            internal ConvHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                ByProgram = new(this);
            }

            protected override object GetPrimaryKey(Conv row) => row.Id;
        }

        public readonly ConvHandle Conv;
    }

    public sealed class ConvCols
    {
        public global::SpacetimeDB.Col<Conv, ulong> Id { get; }
        public global::SpacetimeDB.Col<Conv, ulong> ProgramId { get; }
        public global::SpacetimeDB.Col<Conv, string> Kind { get; }
        public global::SpacetimeDB.NullableCol<Conv, string> SignalCode { get; }
        public global::SpacetimeDB.NullableCol<Conv, string> SignalRegion { get; }
        public global::SpacetimeDB.NullableCol<Conv, System.Collections.Generic.List<ConvVector>> Vectors { get; }
        public global::SpacetimeDB.NullableCol<Conv, string> Diagnosis { get; }
        public global::SpacetimeDB.NullableCol<Conv, string> Timeframe { get; }
        public global::SpacetimeDB.NullableCol<Conv, string> Predicted { get; }
        public global::SpacetimeDB.NullableCol<Conv, string> Rationale { get; }
        public global::SpacetimeDB.NullableCol<Conv, string> Confidence { get; }
        public global::SpacetimeDB.NullableCol<Conv, string> FlagType { get; }
        public global::SpacetimeDB.NullableCol<Conv, string> FlagExpr { get; }
        public global::SpacetimeDB.NullableCol<Conv, string> RiskName { get; }
        public global::SpacetimeDB.NullableCol<Conv, string> RiskTarget { get; }
        public global::SpacetimeDB.NullableCol<Conv, string> RiskDistance { get; }
        public global::SpacetimeDB.NullableCol<Conv, string> RiskWindow { get; }
        public global::SpacetimeDB.NullableCol<Conv, string> RiskReversibleBefore { get; }
        public global::SpacetimeDB.NullableCol<Conv, string> RiskReversibleAfter { get; }
        public global::SpacetimeDB.NullableCol<Conv, string> MonitorMeasurement { get; }
        public global::SpacetimeDB.NullableCol<Conv, string> MonitorFlagRef { get; }
        public global::SpacetimeDB.NullableCol<Conv, string> MonitorNote { get; }

        public ConvCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<Conv, ulong>(tableName, "id");
            ProgramId = new global::SpacetimeDB.Col<Conv, ulong>(tableName, "program_id");
            Kind = new global::SpacetimeDB.Col<Conv, string>(tableName, "kind");
            SignalCode = new global::SpacetimeDB.NullableCol<Conv, string>(tableName, "signal_code");
            SignalRegion = new global::SpacetimeDB.NullableCol<Conv, string>(tableName, "signal_region");
            Vectors = new global::SpacetimeDB.NullableCol<Conv, System.Collections.Generic.List<ConvVector>>(tableName, "vectors");
            Diagnosis = new global::SpacetimeDB.NullableCol<Conv, string>(tableName, "diagnosis");
            Timeframe = new global::SpacetimeDB.NullableCol<Conv, string>(tableName, "timeframe");
            Predicted = new global::SpacetimeDB.NullableCol<Conv, string>(tableName, "predicted");
            Rationale = new global::SpacetimeDB.NullableCol<Conv, string>(tableName, "rationale");
            Confidence = new global::SpacetimeDB.NullableCol<Conv, string>(tableName, "confidence");
            FlagType = new global::SpacetimeDB.NullableCol<Conv, string>(tableName, "flag_type");
            FlagExpr = new global::SpacetimeDB.NullableCol<Conv, string>(tableName, "flag_expr");
            RiskName = new global::SpacetimeDB.NullableCol<Conv, string>(tableName, "risk_name");
            RiskTarget = new global::SpacetimeDB.NullableCol<Conv, string>(tableName, "risk_target");
            RiskDistance = new global::SpacetimeDB.NullableCol<Conv, string>(tableName, "risk_distance");
            RiskWindow = new global::SpacetimeDB.NullableCol<Conv, string>(tableName, "risk_window");
            RiskReversibleBefore = new global::SpacetimeDB.NullableCol<Conv, string>(tableName, "risk_reversible_before");
            RiskReversibleAfter = new global::SpacetimeDB.NullableCol<Conv, string>(tableName, "risk_reversible_after");
            MonitorMeasurement = new global::SpacetimeDB.NullableCol<Conv, string>(tableName, "monitor_measurement");
            MonitorFlagRef = new global::SpacetimeDB.NullableCol<Conv, string>(tableName, "monitor_flag_ref");
            MonitorNote = new global::SpacetimeDB.NullableCol<Conv, string>(tableName, "monitor_note");
        }
    }

    public sealed class ConvIxCols
    {
        public global::SpacetimeDB.IxCol<Conv, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<Conv, ulong> ProgramId { get; }

        public ConvIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<Conv, ulong>(tableName, "id");
            ProgramId = new global::SpacetimeDB.IxCol<Conv, ulong>(tableName, "program_id");
        }
    }
}
