// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class DeltaLogHandle : RemoteTableHandle<EventContext, DeltaLog>
        {
            protected override string RemoteTableName => "delta_log";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(DeltaLog row) => row.Id;

                public IdUniqueIndex(DeltaLogHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class ByProgramIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(DeltaLog row) => row.ProgramId;

                public ByProgramIndex(DeltaLogHandle table) : base(table) { }
            }

            public readonly ByProgramIndex ByProgram;

            internal DeltaLogHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                ByProgram = new(this);
            }

            protected override object GetPrimaryKey(DeltaLog row) => row.Id;
        }

        public readonly DeltaLogHandle DeltaLog;
    }

    public sealed class DeltaLogCols
    {
        public global::SpacetimeDB.Col<DeltaLog, ulong> Id { get; }
        public global::SpacetimeDB.Col<DeltaLog, ulong> ProgramId { get; }
        public global::SpacetimeDB.Col<DeltaLog, ulong> DeltaOpId { get; }
        public global::SpacetimeDB.Col<DeltaLog, uint> FiredAtTick { get; }
        public global::SpacetimeDB.Col<DeltaLog, SpacetimeDB.Timestamp> FiredAt { get; }

        public DeltaLogCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<DeltaLog, ulong>(tableName, "id");
            ProgramId = new global::SpacetimeDB.Col<DeltaLog, ulong>(tableName, "program_id");
            DeltaOpId = new global::SpacetimeDB.Col<DeltaLog, ulong>(tableName, "delta_op_id");
            FiredAtTick = new global::SpacetimeDB.Col<DeltaLog, uint>(tableName, "fired_at_tick");
            FiredAt = new global::SpacetimeDB.Col<DeltaLog, SpacetimeDB.Timestamp>(tableName, "fired_at");
        }
    }

    public sealed class DeltaLogIxCols
    {
        public global::SpacetimeDB.IxCol<DeltaLog, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<DeltaLog, ulong> ProgramId { get; }

        public DeltaLogIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<DeltaLog, ulong>(tableName, "id");
            ProgramId = new global::SpacetimeDB.IxCol<DeltaLog, ulong>(tableName, "program_id");
        }
    }
}
