// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class DiffResultHandle : RemoteTableHandle<EventContext, DiffResult>
        {
            protected override string RemoteTableName => "diff_result";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(DiffResult row) => row.Id;

                public IdUniqueIndex(DiffResultHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class ByProgramIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(DiffResult row) => row.ProgramId;

                public ByProgramIndex(DiffResultHandle table) : base(table) { }
            }

            public readonly ByProgramIndex ByProgram;

            internal DiffResultHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                ByProgram = new(this);
            }

            protected override object GetPrimaryKey(DiffResult row) => row.Id;
        }

        public readonly DiffResultHandle DiffResult;
    }

    public sealed class DiffResultCols
    {
        public global::SpacetimeDB.Col<DiffResult, ulong> Id { get; }
        public global::SpacetimeDB.Col<DiffResult, ulong> ProgramId { get; }
        public global::SpacetimeDB.Col<DiffResult, ulong> SnapA { get; }
        public global::SpacetimeDB.Col<DiffResult, ulong> SnapB { get; }
        public global::SpacetimeDB.Col<DiffResult, System.Collections.Generic.List<SnapshotDiff>> Diffs { get; }
        public global::SpacetimeDB.Col<DiffResult, SpacetimeDB.Timestamp> CreatedAt { get; }

        public DiffResultCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<DiffResult, ulong>(tableName, "id");
            ProgramId = new global::SpacetimeDB.Col<DiffResult, ulong>(tableName, "program_id");
            SnapA = new global::SpacetimeDB.Col<DiffResult, ulong>(tableName, "snap_a");
            SnapB = new global::SpacetimeDB.Col<DiffResult, ulong>(tableName, "snap_b");
            Diffs = new global::SpacetimeDB.Col<DiffResult, System.Collections.Generic.List<SnapshotDiff>>(tableName, "diffs");
            CreatedAt = new global::SpacetimeDB.Col<DiffResult, SpacetimeDB.Timestamp>(tableName, "created_at");
        }
    }

    public sealed class DiffResultIxCols
    {
        public global::SpacetimeDB.IxCol<DiffResult, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<DiffResult, ulong> ProgramId { get; }

        public DiffResultIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<DiffResult, ulong>(tableName, "id");
            ProgramId = new global::SpacetimeDB.IxCol<DiffResult, ulong>(tableName, "program_id");
        }
    }
}
