// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class EdgeHandle : RemoteTableHandle<EventContext, Edge>
        {
            protected override string RemoteTableName => "edge";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(Edge row) => row.Id;

                public IdUniqueIndex(EdgeHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class ByProgramIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(Edge row) => row.ProgramId;

                public ByProgramIndex(EdgeHandle table) : base(table) { }
            }

            public readonly ByProgramIndex ByProgram;

            public sealed class BySourceIndex : BTreeIndexBase<(ulong ProgramId, ulong SourceId)>
            {
                protected override (ulong ProgramId, ulong SourceId) GetKey(Edge row) => (row.ProgramId, row.SourceId);

                public BySourceIndex(EdgeHandle table) : base(table) { }
            }

            public readonly BySourceIndex BySource;

            public sealed class ByTargetIndex : BTreeIndexBase<(ulong ProgramId, ulong TargetId)>
            {
                protected override (ulong ProgramId, ulong TargetId) GetKey(Edge row) => (row.ProgramId, row.TargetId);

                public ByTargetIndex(EdgeHandle table) : base(table) { }
            }

            public readonly ByTargetIndex ByTarget;

            internal EdgeHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                ByProgram = new(this);
                BySource = new(this);
                ByTarget = new(this);
            }

            protected override object GetPrimaryKey(Edge row) => row.Id;
        }

        public readonly EdgeHandle Edge;
    }

    public sealed class EdgeCols
    {
        public global::SpacetimeDB.Col<Edge, ulong> Id { get; }
        public global::SpacetimeDB.Col<Edge, ulong> ProgramId { get; }
        public global::SpacetimeDB.Col<Edge, ulong> SourceId { get; }
        public global::SpacetimeDB.Col<Edge, ulong> TargetId { get; }
        public global::SpacetimeDB.Col<Edge, string> RankTag { get; }
        public global::SpacetimeDB.NullableCol<Edge, string> EdgeType { get; }
        public global::SpacetimeDB.Col<Edge, float> Coeff { get; }
        public global::SpacetimeDB.NullableCol<Edge, GateSpec> Gate { get; }
        public global::SpacetimeDB.NullableCol<Edge, ProtocolSpec> Protocol { get; }
        public global::SpacetimeDB.NullableCol<Edge, string> ProtoLabel { get; }
        public global::SpacetimeDB.NullableCol<Edge, string> Chain { get; }
        public global::SpacetimeDB.NullableCol<Edge, uint> ChainPos { get; }
        public global::SpacetimeDB.NullableCol<Edge, string> RingId { get; }

        public EdgeCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<Edge, ulong>(tableName, "id");
            ProgramId = new global::SpacetimeDB.Col<Edge, ulong>(tableName, "program_id");
            SourceId = new global::SpacetimeDB.Col<Edge, ulong>(tableName, "source_id");
            TargetId = new global::SpacetimeDB.Col<Edge, ulong>(tableName, "target_id");
            RankTag = new global::SpacetimeDB.Col<Edge, string>(tableName, "rank_tag");
            EdgeType = new global::SpacetimeDB.NullableCol<Edge, string>(tableName, "edge_type");
            Coeff = new global::SpacetimeDB.Col<Edge, float>(tableName, "coeff");
            Gate = new global::SpacetimeDB.NullableCol<Edge, GateSpec>(tableName, "gate");
            Protocol = new global::SpacetimeDB.NullableCol<Edge, ProtocolSpec>(tableName, "protocol");
            ProtoLabel = new global::SpacetimeDB.NullableCol<Edge, string>(tableName, "proto_label");
            Chain = new global::SpacetimeDB.NullableCol<Edge, string>(tableName, "chain");
            ChainPos = new global::SpacetimeDB.NullableCol<Edge, uint>(tableName, "chain_pos");
            RingId = new global::SpacetimeDB.NullableCol<Edge, string>(tableName, "ring_id");
        }
    }

    public sealed class EdgeIxCols
    {
        public global::SpacetimeDB.IxCol<Edge, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<Edge, ulong> ProgramId { get; }
        public global::SpacetimeDB.IxCol<Edge, ulong> SourceId { get; }
        public global::SpacetimeDB.IxCol<Edge, ulong> TargetId { get; }

        public EdgeIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<Edge, ulong>(tableName, "id");
            ProgramId = new global::SpacetimeDB.IxCol<Edge, ulong>(tableName, "program_id");
            SourceId = new global::SpacetimeDB.IxCol<Edge, ulong>(tableName, "source_id");
            TargetId = new global::SpacetimeDB.IxCol<Edge, ulong>(tableName, "target_id");
        }
    }
}
