// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class SimTickHandle : RemoteTableHandle<EventContext, SimTick>
        {
            protected override string RemoteTableName => "sim_tick";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(SimTick row) => row.Id;

                public IdUniqueIndex(SimTickHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class ByRunIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(SimTick row) => row.SimRunId;

                public ByRunIndex(SimTickHandle table) : base(table) { }
            }

            public readonly ByRunIndex ByRun;

            public sealed class ByRunTickIndex : BTreeIndexBase<(ulong SimRunId, uint Tick)>
            {
                protected override (ulong SimRunId, uint Tick) GetKey(SimTick row) => (row.SimRunId, row.Tick);

                public ByRunTickIndex(SimTickHandle table) : base(table) { }
            }

            public readonly ByRunTickIndex ByRunTick;

            internal SimTickHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                ByRun = new(this);
                ByRunTick = new(this);
            }

            protected override object GetPrimaryKey(SimTick row) => row.Id;
        }

        public readonly SimTickHandle SimTick;
    }

    public sealed class SimTickCols
    {
        public global::SpacetimeDB.Col<SimTick, ulong> Id { get; }
        public global::SpacetimeDB.Col<SimTick, ulong> SimRunId { get; }
        public global::SpacetimeDB.Col<SimTick, uint> Tick { get; }
        public global::SpacetimeDB.Col<SimTick, ulong> NodeId { get; }
        public global::SpacetimeDB.Col<SimTick, float> Value { get; }
        public global::SpacetimeDB.Col<SimTick, float> Delta { get; }
        public global::SpacetimeDB.Col<SimTick, string> Event { get; }
        public global::SpacetimeDB.Col<SimTick, System.Collections.Generic.List<ulong>> Sources { get; }

        public SimTickCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<SimTick, ulong>(tableName, "id");
            SimRunId = new global::SpacetimeDB.Col<SimTick, ulong>(tableName, "sim_run_id");
            Tick = new global::SpacetimeDB.Col<SimTick, uint>(tableName, "tick");
            NodeId = new global::SpacetimeDB.Col<SimTick, ulong>(tableName, "node_id");
            Value = new global::SpacetimeDB.Col<SimTick, float>(tableName, "value");
            Delta = new global::SpacetimeDB.Col<SimTick, float>(tableName, "delta");
            Event = new global::SpacetimeDB.Col<SimTick, string>(tableName, "event");
            Sources = new global::SpacetimeDB.Col<SimTick, System.Collections.Generic.List<ulong>>(tableName, "sources");
        }
    }

    public sealed class SimTickIxCols
    {
        public global::SpacetimeDB.IxCol<SimTick, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<SimTick, ulong> SimRunId { get; }
        public global::SpacetimeDB.IxCol<SimTick, uint> Tick { get; }

        public SimTickIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<SimTick, ulong>(tableName, "id");
            SimRunId = new global::SpacetimeDB.IxCol<SimTick, ulong>(tableName, "sim_run_id");
            Tick = new global::SpacetimeDB.IxCol<SimTick, uint>(tableName, "tick");
        }
    }
}
