// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class SnapshotEdgeHandle : RemoteTableHandle<EventContext, SnapshotEdge>
        {
            protected override string RemoteTableName => "snapshot_edge";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(SnapshotEdge row) => row.Id;

                public IdUniqueIndex(SnapshotEdgeHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class BySnapshotIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(SnapshotEdge row) => row.SnapshotId;

                public BySnapshotIndex(SnapshotEdgeHandle table) : base(table) { }
            }

            public readonly BySnapshotIndex BySnapshot;

            internal SnapshotEdgeHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                BySnapshot = new(this);
            }

            protected override object GetPrimaryKey(SnapshotEdge row) => row.Id;
        }

        public readonly SnapshotEdgeHandle SnapshotEdge;
    }

    public sealed class SnapshotEdgeCols
    {
        public global::SpacetimeDB.Col<SnapshotEdge, ulong> Id { get; }
        public global::SpacetimeDB.Col<SnapshotEdge, ulong> SnapshotId { get; }
        public global::SpacetimeDB.Col<SnapshotEdge, ulong> EdgeId { get; }
        public global::SpacetimeDB.Col<SnapshotEdge, float> Coeff { get; }
        public global::SpacetimeDB.NullableCol<SnapshotEdge, float> Gain { get; }

        public SnapshotEdgeCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<SnapshotEdge, ulong>(tableName, "id");
            SnapshotId = new global::SpacetimeDB.Col<SnapshotEdge, ulong>(tableName, "snapshot_id");
            EdgeId = new global::SpacetimeDB.Col<SnapshotEdge, ulong>(tableName, "edge_id");
            Coeff = new global::SpacetimeDB.Col<SnapshotEdge, float>(tableName, "coeff");
            Gain = new global::SpacetimeDB.NullableCol<SnapshotEdge, float>(tableName, "gain");
        }
    }

    public sealed class SnapshotEdgeIxCols
    {
        public global::SpacetimeDB.IxCol<SnapshotEdge, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<SnapshotEdge, ulong> SnapshotId { get; }

        public SnapshotEdgeIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<SnapshotEdge, ulong>(tableName, "id");
            SnapshotId = new global::SpacetimeDB.IxCol<SnapshotEdge, ulong>(tableName, "snapshot_id");
        }
    }
}
