// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class DiagHandle : RemoteTableHandle<EventContext, Diag>
        {
            protected override string RemoteTableName => "diag";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(Diag row) => row.Id;

                public IdUniqueIndex(DiagHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class ByProgramIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(Diag row) => row.ProgramId;

                public ByProgramIndex(DiagHandle table) : base(table) { }
            }

            public readonly ByProgramIndex ByProgram;

            internal DiagHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                ByProgram = new(this);
            }

            protected override object GetPrimaryKey(Diag row) => row.Id;
        }

        public readonly DiagHandle Diag;
    }

    public sealed class DiagCols
    {
        public global::SpacetimeDB.Col<Diag, ulong> Id { get; }
        public global::SpacetimeDB.Col<Diag, ulong> ProgramId { get; }
        public global::SpacetimeDB.Col<Diag, string> Kind { get; }
        public global::SpacetimeDB.NullableCol<Diag, string> Name { get; }
        public global::SpacetimeDB.Col<Diag, string> Expr { get; }
        public global::SpacetimeDB.Col<Diag, System.Collections.Generic.List<Kv>> Detail { get; }

        public DiagCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<Diag, ulong>(tableName, "id");
            ProgramId = new global::SpacetimeDB.Col<Diag, ulong>(tableName, "program_id");
            Kind = new global::SpacetimeDB.Col<Diag, string>(tableName, "kind");
            Name = new global::SpacetimeDB.NullableCol<Diag, string>(tableName, "name");
            Expr = new global::SpacetimeDB.Col<Diag, string>(tableName, "expr");
            Detail = new global::SpacetimeDB.Col<Diag, System.Collections.Generic.List<Kv>>(tableName, "detail");
        }
    }

    public sealed class DiagIxCols
    {
        public global::SpacetimeDB.IxCol<Diag, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<Diag, ulong> ProgramId { get; }

        public DiagIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<Diag, ulong>(tableName, "id");
            ProgramId = new global::SpacetimeDB.IxCol<Diag, ulong>(tableName, "program_id");
        }
    }
}
