// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class MetaOpHandle : RemoteTableHandle<EventContext, MetaOp>
        {
            protected override string RemoteTableName => "meta_op";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(MetaOp row) => row.Id;

                public IdUniqueIndex(MetaOpHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class ByProgramIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(MetaOp row) => row.ProgramId;

                public ByProgramIndex(MetaOpHandle table) : base(table) { }
            }

            public readonly ByProgramIndex ByProgram;

            public sealed class ByRankIndex : BTreeIndexBase<(ulong ProgramId, string RankTag)>
            {
                protected override (ulong ProgramId, string RankTag) GetKey(MetaOp row) => (row.ProgramId, row.RankTag);

                public ByRankIndex(MetaOpHandle table) : base(table) { }
            }

            public readonly ByRankIndex ByRank;

            internal MetaOpHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                ByProgram = new(this);
                ByRank = new(this);
            }

            protected override object GetPrimaryKey(MetaOp row) => row.Id;
        }

        public readonly MetaOpHandle MetaOp;
    }

    public sealed class MetaOpCols
    {
        public global::SpacetimeDB.Col<MetaOp, ulong> Id { get; }
        public global::SpacetimeDB.Col<MetaOp, ulong> ProgramId { get; }
        public global::SpacetimeDB.Col<MetaOp, string> RankTag { get; }
        public global::SpacetimeDB.Col<MetaOp, MetaWindow> Window { get; }
        public global::SpacetimeDB.Col<MetaOp, MetaTarget> Target { get; }

        public MetaOpCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<MetaOp, ulong>(tableName, "id");
            ProgramId = new global::SpacetimeDB.Col<MetaOp, ulong>(tableName, "program_id");
            RankTag = new global::SpacetimeDB.Col<MetaOp, string>(tableName, "rank_tag");
            Window = new global::SpacetimeDB.Col<MetaOp, MetaWindow>(tableName, "window");
            Target = new global::SpacetimeDB.Col<MetaOp, MetaTarget>(tableName, "target");
        }
    }

    public sealed class MetaOpIxCols
    {
        public global::SpacetimeDB.IxCol<MetaOp, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<MetaOp, ulong> ProgramId { get; }
        public global::SpacetimeDB.IxCol<MetaOp, string> RankTag { get; }

        public MetaOpIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<MetaOp, ulong>(tableName, "id");
            ProgramId = new global::SpacetimeDB.IxCol<MetaOp, ulong>(tableName, "program_id");
            RankTag = new global::SpacetimeDB.IxCol<MetaOp, string>(tableName, "rank_tag");
        }
    }
}
