// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class NodeHandle : RemoteTableHandle<EventContext, Node>
        {
            protected override string RemoteTableName => "node";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(Node row) => row.Id;

                public IdUniqueIndex(NodeHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class ByProgramIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(Node row) => row.ProgramId;

                public ByProgramIndex(NodeHandle table) : base(table) { }
            }

            public readonly ByProgramIndex ByProgram;

            public sealed class ByProgramRankIndex : BTreeIndexBase<(ulong ProgramId, string RankTag)>
            {
                protected override (ulong ProgramId, string RankTag) GetKey(Node row) => (row.ProgramId, row.RankTag);

                public ByProgramRankIndex(NodeHandle table) : base(table) { }
            }

            public readonly ByProgramRankIndex ByProgramRank;

            internal NodeHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                ByProgram = new(this);
                ByProgramRank = new(this);
            }

            protected override object GetPrimaryKey(Node row) => row.Id;
        }

        public readonly NodeHandle Node;
    }

    public sealed class NodeCols
    {
        public global::SpacetimeDB.Col<Node, ulong> Id { get; }
        public global::SpacetimeDB.Col<Node, ulong> ProgramId { get; }
        public global::SpacetimeDB.Col<Node, string> Code { get; }
        public global::SpacetimeDB.Col<Node, string> Kind { get; }
        public global::SpacetimeDB.NullableCol<Node, string> Region { get; }
        public global::SpacetimeDB.Col<Node, string> RankTag { get; }
        public global::SpacetimeDB.NullableCol<Node, NodeState> State { get; }
        public global::SpacetimeDB.NullableCol<Node, Integration> Integ { get; }
        public global::SpacetimeDB.Col<Node, System.Collections.Generic.List<Kv>> Props { get; }
        public global::SpacetimeDB.Col<Node, bool> IsRoot { get; }
        public global::SpacetimeDB.NullableCol<Node, string> Terminal { get; }

        public NodeCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<Node, ulong>(tableName, "id");
            ProgramId = new global::SpacetimeDB.Col<Node, ulong>(tableName, "program_id");
            Code = new global::SpacetimeDB.Col<Node, string>(tableName, "code");
            Kind = new global::SpacetimeDB.Col<Node, string>(tableName, "kind");
            Region = new global::SpacetimeDB.NullableCol<Node, string>(tableName, "region");
            RankTag = new global::SpacetimeDB.Col<Node, string>(tableName, "rank_tag");
            State = new global::SpacetimeDB.NullableCol<Node, NodeState>(tableName, "state");
            Integ = new global::SpacetimeDB.NullableCol<Node, Integration>(tableName, "integ");
            Props = new global::SpacetimeDB.Col<Node, System.Collections.Generic.List<Kv>>(tableName, "props");
            IsRoot = new global::SpacetimeDB.Col<Node, bool>(tableName, "is_root");
            Terminal = new global::SpacetimeDB.NullableCol<Node, string>(tableName, "terminal");
        }
    }

    public sealed class NodeIxCols
    {
        public global::SpacetimeDB.IxCol<Node, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<Node, ulong> ProgramId { get; }
        public global::SpacetimeDB.IxCol<Node, string> RankTag { get; }

        public NodeIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<Node, ulong>(tableName, "id");
            ProgramId = new global::SpacetimeDB.IxCol<Node, ulong>(tableName, "program_id");
            RankTag = new global::SpacetimeDB.IxCol<Node, string>(tableName, "rank_tag");
        }
    }
}
