// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class SnapshotNodeHandle : RemoteTableHandle<EventContext, SnapshotNode>
        {
            protected override string RemoteTableName => "snapshot_node";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(SnapshotNode row) => row.Id;

                public IdUniqueIndex(SnapshotNodeHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class BySnapshotIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(SnapshotNode row) => row.SnapshotId;

                public BySnapshotIndex(SnapshotNodeHandle table) : base(table) { }
            }

            public readonly BySnapshotIndex BySnapshot;

            internal SnapshotNodeHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                BySnapshot = new(this);
            }

            protected override object GetPrimaryKey(SnapshotNode row) => row.Id;
        }

        public readonly SnapshotNodeHandle SnapshotNode;
    }

    public sealed class SnapshotNodeCols
    {
        public global::SpacetimeDB.Col<SnapshotNode, ulong> Id { get; }
        public global::SpacetimeDB.Col<SnapshotNode, ulong> SnapshotId { get; }
        public global::SpacetimeDB.Col<SnapshotNode, ulong> NodeId { get; }
        public global::SpacetimeDB.Col<SnapshotNode, string> Code { get; }
        public global::SpacetimeDB.NullableCol<SnapshotNode, string> Region { get; }
        public global::SpacetimeDB.NullableCol<SnapshotNode, string> StateSym { get; }
        public global::SpacetimeDB.NullableCol<SnapshotNode, float> StateVal { get; }

        public SnapshotNodeCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<SnapshotNode, ulong>(tableName, "id");
            SnapshotId = new global::SpacetimeDB.Col<SnapshotNode, ulong>(tableName, "snapshot_id");
            NodeId = new global::SpacetimeDB.Col<SnapshotNode, ulong>(tableName, "node_id");
            Code = new global::SpacetimeDB.Col<SnapshotNode, string>(tableName, "code");
            Region = new global::SpacetimeDB.NullableCol<SnapshotNode, string>(tableName, "region");
            StateSym = new global::SpacetimeDB.NullableCol<SnapshotNode, string>(tableName, "state_sym");
            StateVal = new global::SpacetimeDB.NullableCol<SnapshotNode, float>(tableName, "state_val");
        }
    }

    public sealed class SnapshotNodeIxCols
    {
        public global::SpacetimeDB.IxCol<SnapshotNode, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<SnapshotNode, ulong> SnapshotId { get; }

        public SnapshotNodeIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<SnapshotNode, ulong>(tableName, "id");
            SnapshotId = new global::SpacetimeDB.IxCol<SnapshotNode, ulong>(tableName, "snapshot_id");
        }
    }
}
