// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class TauAccHandle : RemoteTableHandle<EventContext, TauAccumulator>
        {
            protected override string RemoteTableName => "tau_acc";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(TauAccumulator row) => row.Id;

                public IdUniqueIndex(TauAccHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class ByRunIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(TauAccumulator row) => row.SimRunId;

                public ByRunIndex(TauAccHandle table) : base(table) { }
            }

            public readonly ByRunIndex ByRun;

            internal TauAccHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                ByRun = new(this);
            }

            protected override object GetPrimaryKey(TauAccumulator row) => row.Id;
        }

        public readonly TauAccHandle TauAcc;
    }

    public sealed class TauAccCols
    {
        public global::SpacetimeDB.Col<TauAccumulator, ulong> Id { get; }
        public global::SpacetimeDB.Col<TauAccumulator, ulong> SimRunId { get; }
        public global::SpacetimeDB.Col<TauAccumulator, ulong> TriggerId { get; }
        public global::SpacetimeDB.Col<TauAccumulator, string> TriggerKind { get; }
        public global::SpacetimeDB.Col<TauAccumulator, float> Accumulated { get; }
        public global::SpacetimeDB.Col<TauAccumulator, float> TauTarget { get; }

        public TauAccCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<TauAccumulator, ulong>(tableName, "id");
            SimRunId = new global::SpacetimeDB.Col<TauAccumulator, ulong>(tableName, "sim_run_id");
            TriggerId = new global::SpacetimeDB.Col<TauAccumulator, ulong>(tableName, "trigger_id");
            TriggerKind = new global::SpacetimeDB.Col<TauAccumulator, string>(tableName, "trigger_kind");
            Accumulated = new global::SpacetimeDB.Col<TauAccumulator, float>(tableName, "accumulated");
            TauTarget = new global::SpacetimeDB.Col<TauAccumulator, float>(tableName, "tau_target");
        }
    }

    public sealed class TauAccIxCols
    {
        public global::SpacetimeDB.IxCol<TauAccumulator, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<TauAccumulator, ulong> SimRunId { get; }

        public TauAccIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<TauAccumulator, ulong>(tableName, "id");
            SimRunId = new global::SpacetimeDB.IxCol<TauAccumulator, ulong>(tableName, "sim_run_id");
        }
    }
}
