// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AddDiagHandler(ReducerEventContext ctx, ulong programId, string kind, string? name, string expr, System.Collections.Generic.List<SpacetimeDB.Types.Kv> detail);
        public event AddDiagHandler? OnAddDiag;

        public void AddDiag(ulong programId, string kind, string? name, string expr, System.Collections.Generic.List<SpacetimeDB.Types.Kv> detail)
        {
            conn.InternalCallReducer(new Reducer.AddDiag(programId, kind, name, expr, detail));
        }

        public bool InvokeAddDiag(ReducerEventContext ctx, Reducer.AddDiag args)
        {
            if (OnAddDiag == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAddDiag(
                ctx,
                args.ProgramId,
                args.Kind,
                args.Name,
                args.Expr,
                args.Detail
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AddDiag : Reducer, IReducerArgs
        {
            [DataMember(Name = "program_id")]
            public ulong ProgramId;
            [DataMember(Name = "kind")]
            public string Kind;
            [DataMember(Name = "name")]
            public string? Name;
            [DataMember(Name = "expr")]
            public string Expr;
            [DataMember(Name = "detail")]
            public System.Collections.Generic.List<Kv> Detail;

            public AddDiag(
                ulong ProgramId,
                string Kind,
                string? Name,
                string Expr,
                System.Collections.Generic.List<Kv> Detail
            )
            {
                this.ProgramId = ProgramId;
                this.Kind = Kind;
                this.Name = Name;
                this.Expr = Expr;
                this.Detail = Detail;
            }

            public AddDiag()
            {
                this.Kind = "";
                this.Expr = "";
                this.Detail = new();
            }

            string IReducerArgs.ReducerName => "add_diag";
        }
    }
}
