// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AddEdgeHandler(ReducerEventContext ctx, ulong programId, ulong sourceId, ulong targetId, string rankTag, string? edgeType, float coeff, SpacetimeDB.Types.GateSpec? gate, SpacetimeDB.Types.ProtocolSpec? protocol, string? protoLabel, string? chain, uint? chainPos, string? ringId);
        public event AddEdgeHandler? OnAddEdge;

        public void AddEdge(ulong programId, ulong sourceId, ulong targetId, string rankTag, string? edgeType, float coeff, SpacetimeDB.Types.GateSpec? gate, SpacetimeDB.Types.ProtocolSpec? protocol, string? protoLabel, string? chain, uint? chainPos, string? ringId)
        {
            conn.InternalCallReducer(new Reducer.AddEdge(programId, sourceId, targetId, rankTag, edgeType, coeff, gate, protocol, protoLabel, chain, chainPos, ringId));
        }

        public bool InvokeAddEdge(ReducerEventContext ctx, Reducer.AddEdge args)
        {
            if (OnAddEdge == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAddEdge(
                ctx,
                args.ProgramId,
                args.SourceId,
                args.TargetId,
                args.RankTag,
                args.EdgeType,
                args.Coeff,
                args.Gate,
                args.Protocol,
                args.ProtoLabel,
                args.Chain,
                args.ChainPos,
                args.RingId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AddEdge : Reducer, IReducerArgs
        {
            [DataMember(Name = "program_id")]
            public ulong ProgramId;
            [DataMember(Name = "source_id")]
            public ulong SourceId;
            [DataMember(Name = "target_id")]
            public ulong TargetId;
            [DataMember(Name = "rank_tag")]
            public string RankTag;
            [DataMember(Name = "edge_type")]
            public string? EdgeType;
            [DataMember(Name = "coeff")]
            public float Coeff;
            [DataMember(Name = "gate")]
            public GateSpec? Gate;
            [DataMember(Name = "protocol")]
            public ProtocolSpec? Protocol;
            [DataMember(Name = "proto_label")]
            public string? ProtoLabel;
            [DataMember(Name = "chain")]
            public string? Chain;
            [DataMember(Name = "chain_pos")]
            public uint? ChainPos;
            [DataMember(Name = "ring_id")]
            public string? RingId;

            public AddEdge(
                ulong ProgramId,
                ulong SourceId,
                ulong TargetId,
                string RankTag,
                string? EdgeType,
                float Coeff,
                GateSpec? Gate,
                ProtocolSpec? Protocol,
                string? ProtoLabel,
                string? Chain,
                uint? ChainPos,
                string? RingId
            )
            {
                this.ProgramId = ProgramId;
                this.SourceId = SourceId;
                this.TargetId = TargetId;
                this.RankTag = RankTag;
                this.EdgeType = EdgeType;
                this.Coeff = Coeff;
                this.Gate = Gate;
                this.Protocol = Protocol;
                this.ProtoLabel = ProtoLabel;
                this.Chain = Chain;
                this.ChainPos = ChainPos;
                this.RingId = RingId;
            }

            public AddEdge()
            {
                this.RankTag = "";
            }

            string IReducerArgs.ReducerName => "add_edge";
        }
    }
}
