// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AddMetaHandler(ReducerEventContext ctx, ulong programId, string rankTag, SpacetimeDB.Types.MetaWindow window, SpacetimeDB.Types.MetaTarget target);
        public event AddMetaHandler? OnAddMeta;

        public void AddMeta(ulong programId, string rankTag, SpacetimeDB.Types.MetaWindow window, SpacetimeDB.Types.MetaTarget target)
        {
            conn.InternalCallReducer(new Reducer.AddMeta(programId, rankTag, window, target));
        }

        public bool InvokeAddMeta(ReducerEventContext ctx, Reducer.AddMeta args)
        {
            if (OnAddMeta == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAddMeta(
                ctx,
                args.ProgramId,
                args.RankTag,
                args.Window,
                args.Target
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AddMeta : Reducer, IReducerArgs
        {
            [DataMember(Name = "program_id")]
            public ulong ProgramId;
            [DataMember(Name = "rank_tag")]
            public string RankTag;
            [DataMember(Name = "window")]
            public MetaWindow Window;
            [DataMember(Name = "target")]
            public MetaTarget Target;

            public AddMeta(
                ulong ProgramId,
                string RankTag,
                MetaWindow Window,
                MetaTarget Target
            )
            {
                this.ProgramId = ProgramId;
                this.RankTag = RankTag;
                this.Window = Window;
                this.Target = Target;
            }

            public AddMeta()
            {
                this.RankTag = "";
                this.Window = new();
                this.Target = new();
            }

            string IReducerArgs.ReducerName => "add_meta";
        }
    }
}
