// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ComputeConvergenceHandler(ReducerEventContext ctx, ulong programId);
        public event ComputeConvergenceHandler? OnComputeConvergence;

        public void ComputeConvergence(ulong programId)
        {
            conn.InternalCallReducer(new Reducer.ComputeConvergence(programId));
        }

        public bool InvokeComputeConvergence(ReducerEventContext ctx, Reducer.ComputeConvergence args)
        {
            if (OnComputeConvergence == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnComputeConvergence(
                ctx,
                args.ProgramId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ComputeConvergence : Reducer, IReducerArgs
        {
            [DataMember(Name = "program_id")]
            public ulong ProgramId;

            public ComputeConvergence(ulong ProgramId)
            {
                this.ProgramId = ProgramId;
            }

            public ComputeConvergence()
            {
            }

            string IReducerArgs.ReducerName => "compute_convergence";
        }
    }
}
