// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CreateProgramHandler(ReducerEventContext ctx, string name, string? phase, System.Collections.Generic.List<string> domains);
        public event CreateProgramHandler? OnCreateProgram;

        public void CreateProgram(string name, string? phase, System.Collections.Generic.List<string> domains)
        {
            conn.InternalCallReducer(new Reducer.CreateProgram(name, phase, domains));
        }

        public bool InvokeCreateProgram(ReducerEventContext ctx, Reducer.CreateProgram args)
        {
            if (OnCreateProgram == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnCreateProgram(
                ctx,
                args.Name,
                args.Phase,
                args.Domains
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CreateProgram : Reducer, IReducerArgs
        {
            [DataMember(Name = "name")]
            public string Name;
            [DataMember(Name = "phase")]
            public string? Phase;
            [DataMember(Name = "domains")]
            public System.Collections.Generic.List<string> Domains;

            public CreateProgram(
                string Name,
                string? Phase,
                System.Collections.Generic.List<string> Domains
            )
            {
                this.Name = Name;
                this.Phase = Phase;
                this.Domains = Domains;
            }

            public CreateProgram()
            {
                this.Name = "";
                this.Domains = new();
            }

            string IReducerArgs.ReducerName => "create_program";
        }
    }
}
