// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void GetEvidenceTraceHandler(ReducerEventContext ctx, ulong simRunId);
        public event GetEvidenceTraceHandler? OnGetEvidenceTrace;

        public void GetEvidenceTrace(ulong simRunId)
        {
            conn.InternalCallReducer(new Reducer.GetEvidenceTrace(simRunId));
        }

        public bool InvokeGetEvidenceTrace(ReducerEventContext ctx, Reducer.GetEvidenceTrace args)
        {
            if (OnGetEvidenceTrace == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnGetEvidenceTrace(
                ctx,
                args.SimRunId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class GetEvidenceTrace : Reducer, IReducerArgs
        {
            [DataMember(Name = "sim_run_id")]
            public ulong SimRunId;

            public GetEvidenceTrace(ulong SimRunId)
            {
                this.SimRunId = SimRunId;
            }

            public GetEvidenceTrace()
            {
            }

            string IReducerArgs.ReducerName => "get_evidence_trace";
        }
    }
}
