// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void QueryDeltasHandler(ReducerEventContext ctx, ulong programId, string? rankTag);
        public event QueryDeltasHandler? OnQueryDeltas;

        public void QueryDeltas(ulong programId, string? rankTag)
        {
            conn.InternalCallReducer(new Reducer.QueryDeltas(programId, rankTag));
        }

        public bool InvokeQueryDeltas(ReducerEventContext ctx, Reducer.QueryDeltas args)
        {
            if (OnQueryDeltas == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnQueryDeltas(
                ctx,
                args.ProgramId,
                args.RankTag
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class QueryDeltas : Reducer, IReducerArgs
        {
            [DataMember(Name = "program_id")]
            public ulong ProgramId;
            [DataMember(Name = "rank_tag")]
            public string? RankTag;

            public QueryDeltas(
                ulong ProgramId,
                string? RankTag
            )
            {
                this.ProgramId = ProgramId;
                this.RankTag = RankTag;
            }

            public QueryDeltas()
            {
            }

            string IReducerArgs.ReducerName => "query_deltas";
        }
    }
}
