// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void QueryGraphHandler(ReducerEventContext ctx, ulong programId, string rankTag);
        public event QueryGraphHandler? OnQueryGraph;

        public void QueryGraph(ulong programId, string rankTag)
        {
            conn.InternalCallReducer(new Reducer.QueryGraph(programId, rankTag));
        }

        public bool InvokeQueryGraph(ReducerEventContext ctx, Reducer.QueryGraph args)
        {
            if (OnQueryGraph == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnQueryGraph(
                ctx,
                args.ProgramId,
                args.RankTag
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class QueryGraph : Reducer, IReducerArgs
        {
            [DataMember(Name = "program_id")]
            public ulong ProgramId;
            [DataMember(Name = "rank_tag")]
            public string RankTag;

            public QueryGraph(
                ulong ProgramId,
                string RankTag
            )
            {
                this.ProgramId = ProgramId;
                this.RankTag = RankTag;
            }

            public QueryGraph()
            {
                this.RankTag = "";
            }

            string IReducerArgs.ReducerName => "query_graph";
        }
    }
}
