// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ReconstructHandler(ReducerEventContext ctx, ulong programId);
        public event ReconstructHandler? OnReconstruct;

        public void Reconstruct(ulong programId)
        {
            conn.InternalCallReducer(new Reducer.Reconstruct(programId));
        }

        public bool InvokeReconstruct(ReducerEventContext ctx, Reducer.Reconstruct args)
        {
            if (OnReconstruct == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnReconstruct(
                ctx,
                args.ProgramId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class Reconstruct : Reducer, IReducerArgs
        {
            [DataMember(Name = "program_id")]
            public ulong ProgramId;

            public Reconstruct(ulong ProgramId)
            {
                this.ProgramId = ProgramId;
            }

            public Reconstruct()
            {
            }

            string IReducerArgs.ReducerName => "reconstruct";
        }
    }
}
