// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SimulateHandler(ReducerEventContext ctx, ulong programId, System.Collections.Generic.List<SpacetimeDB.Types.Perturbation> perturbations, uint maxTicks);
        public event SimulateHandler? OnSimulate;

        public void Simulate(ulong programId, System.Collections.Generic.List<SpacetimeDB.Types.Perturbation> perturbations, uint maxTicks)
        {
            conn.InternalCallReducer(new Reducer.Simulate(programId, perturbations, maxTicks));
        }

        public bool InvokeSimulate(ReducerEventContext ctx, Reducer.Simulate args)
        {
            if (OnSimulate == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSimulate(
                ctx,
                args.ProgramId,
                args.Perturbations,
                args.MaxTicks
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class Simulate : Reducer, IReducerArgs
        {
            [DataMember(Name = "program_id")]
            public ulong ProgramId;
            [DataMember(Name = "perturbations")]
            public System.Collections.Generic.List<Perturbation> Perturbations;
            [DataMember(Name = "max_ticks")]
            public uint MaxTicks;

            public Simulate(
                ulong ProgramId,
                System.Collections.Generic.List<Perturbation> Perturbations,
                uint MaxTicks
            )
            {
                this.ProgramId = ProgramId;
                this.Perturbations = Perturbations;
                this.MaxTicks = MaxTicks;
            }

            public Simulate()
            {
                this.Perturbations = new();
            }

            string IReducerArgs.ReducerName => "simulate";
        }
    }
}
