// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void StoreRawBnfHandler(ReducerEventContext ctx, ulong programId, string pipeline, string raw);
        public event StoreRawBnfHandler? OnStoreRawBnf;

        public void StoreRawBnf(ulong programId, string pipeline, string raw)
        {
            conn.InternalCallReducer(new Reducer.StoreRawBnf(programId, pipeline, raw));
        }

        public bool InvokeStoreRawBnf(ReducerEventContext ctx, Reducer.StoreRawBnf args)
        {
            if (OnStoreRawBnf == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnStoreRawBnf(
                ctx,
                args.ProgramId,
                args.Pipeline,
                args.Raw
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class StoreRawBnf : Reducer, IReducerArgs
        {
            [DataMember(Name = "program_id")]
            public ulong ProgramId;
            [DataMember(Name = "pipeline")]
            public string Pipeline;
            [DataMember(Name = "raw")]
            public string Raw;

            public StoreRawBnf(
                ulong ProgramId,
                string Pipeline,
                string Raw
            )
            {
                this.ProgramId = ProgramId;
                this.Pipeline = Pipeline;
                this.Raw = Raw;
            }

            public StoreRawBnf()
            {
                this.Pipeline = "";
                this.Raw = "";
            }

            string IReducerArgs.ReducerName => "store_raw_bnf";
        }
    }
}
