<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>NeuroGateway.AnalysisFramework</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="OLD\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Libraries\NeuroGateway.Models\NeuroGateway.Models.csproj" />
  </ItemGroup>

</Project>
