namespace BioChain.AnalysisFramework.BigFive;

// Big Five (OCEAN) prototype descriptions per chemical.
// Each pole emphasizes DIFFERENT chemicals with genuinely distinct vocabulary,
// so embedding vectors are naturally far apart in semantic space.
// HIGH poles describe chemicals that drive that trait direction;
// LOW poles describe different chemicals that drive the opposite direction.
// This avoids the pitfall of "dopamine elevated" vs "dopamine low" sharing
// 80% vocabulary and producing near-identical embeddings.
//
// PrototypeVersion must be bumped whenever descriptions change to force re-embedding.
public static class BigFivePrototypes
{
    public const int PrototypeVersion = 3;

    public static readonly Dictionary<(string Pole, string Chemical), string> ChemicalDescriptions = new()
    {
        // ══════════════════════════════════════════════════════════════
        // OPENNESS HIGH — curious, creative, abstract, novelty-seeking
        // Lead chemicals: dopamine, glutamate, bdnf, endocannabinoid, norepinephrine, acetylcholine, orexin, dhea, thyroid
        // ══════════════════════════════════════════════════════════════
        [("openness_high", "dopamine")] = "Novelty-driven exploration fueled by D4 receptor polymorphism in prefrontal cortex. VTA phasic bursting generates anticipatory excitement for unfamiliar stimuli. Divergent thinking emerges from mesolimbic reward for discovering unexpected patterns. Creative association and intellectual risk-taking rewarded through ventral striatal activation.",
        [("openness_high", "glutamate")] = "NMDA receptor NR2B subunits in hippocampus enable extended coincidence detection for remote conceptual associations. Synaptic plasticity supports rapid formation of novel cross-domain connections. Metabotropic mGluR5 activation in prefrontal cortex drives creative insight and abstract reasoning. Mental frameworks assembled through excitatory cascade.",
        [("openness_high", "bdnf")] = "Rapid neuroplasticity through TrkB signaling in hippocampus and cortex. Val66Val polymorphism with high activity-dependent secretion enables fast encoding of novel frameworks. BDNF-CREB cascade supports learning new paradigms and abstract conceptual models. Neural growth factor for intellectual expansion.",
        [("openness_high", "endocannabinoid")] = "CB1 retrograde signaling loosens rigid top-down perceptual constraints. Anandamide tone in prefrontal cortex supports cognitive flexibility and openness to alternative perspectives. 2-AG modulation enhances divergent processing and free-associative thought. Inner perceptual boundaries become fluid and permeable.",
        [("openness_high", "norepinephrine")] = "Locus coeruleus tonic mode enables broad attentional scanning across conceptual domains. Moderate arousal optimized for detecting unexpected connections between disparate ideas. Cognitive flexibility sustained through alpha-2A receptor engagement without tunnel vision. Wide-lens awareness scanning for novelty.",
        [("openness_high", "acetylcholine")] = "Muscarinic M1 receptor activation in entorhinal cortex supports associative memory linking across domains. Nucleus basalis projections enhance cross-domain pattern recognition and intellectual curiosity. Deep encoding of novel concepts through cholinergic attentional engagement. Knowledge integration across disciplines.",
        [("openness_high", "orexin")] = "OX1R/OX2R activation drives sustained wakefulness and motivational arousal for exploration. Lateral hypothalamic neurons fuel curiosity-driven energy for late-night ideation and discovery. Arousal system calibrated for adventure and intellectual pursuit rather than routine maintenance.",
        [("openness_high", "dhea")] = "High DHEA:cortisol ratio supports resilient exploration under uncertainty. Neurosteroid modulation preserves cognitive flexibility when navigating unfamiliar territory. Anti-stress buffering enables sustained creative engagement without defensive withdrawal.",
        [("openness_high", "thyroid")] = "TRα/TRβ receptor activation supports fast cognitive processing speed for rapid association formation. Mitochondrial energy in cortical neurons fuels extended creative cognition and abstract model-building.",

        // ══════════════════════════════════════════════════════════════
        // OPENNESS LOW — conventional, concrete, practical, routine-preferring
        // Lead chemicals: serotonin, gaba, vasopressin, cortisol, melatonin, progesterone, prolactin, dynorphin, crh
        // ══════════════════════════════════════════════════════════════
        [("openness_low", "serotonin")] = "Elevated 5-HT2A receptor density in sensory cortex anchors attention to concrete present-moment perception. Tryptophan hydroxylase-2 activity pattern favoring sensory precision over imagination. Stable dorsal raphe output calms the mind into practical clarity. Grounded awareness of tangible reality.",
        [("openness_low", "gaba")] = "Strong GABAergic inhibition in default mode network suppresses unstructured ideation and fantasy. PV+ interneuron tonic inhibition constrains associations to conventional semantic categories. Structured thought architecture preferred over free-association. Mental discipline through inhibitory braking.",
        [("openness_low", "vasopressin")] = "V1a receptor activation supports loyalty to established traditions and proven methods. Territorial maintenance of conventional worldview and familiar practices. Protective instinct toward tested approaches and institutional knowledge. Stability through precedent.",
        [("openness_low", "cortisol")] = "GR activation in amygdala creates mild aversion to ambiguous or unstructured situations. HPA axis reactivity treats novelty as potential threat requiring caution. Anticipatory stress response channels energy toward proven solutions. Safety in the known and tested.",
        [("openness_low", "melatonin")] = "MT1/MT2 receptor sensitivity precisely calibrated for consistent circadian rhythm. Pineal gland secretion supporting disciplined sleep-wake cycles and regular daily structure. Biological clock aligned with conventional scheduling and routine maintenance.",
        [("openness_low", "progesterone")] = "Allopregnanolone GABA-A positive modulation supports calm routine adherence and preference for predictable schedules. Sedating neurosteroid effect compatible with settled, structured lifestyle. Contentment within established frameworks.",
        [("openness_low", "prolactin")] = "Dopamine-prolactin balance shifted toward contentment with established knowledge. Satiation signal reduces drive to seek novel intellectual stimulation. Comfortable mastery of known domains preferred over restless exploration.",
        [("openness_low", "dynorphin")] = "Kappa-opioid receptor activation when forced out of comfort zone signals return to established patterns. KOR-mediated aversion creates discomfort with unfamiliar abstract concepts. Neurochemical preference for the concrete and proven.",
        [("openness_low", "crh")] = "CRHR1 activation triggered by open-ended ambiguity drives closure-seeking behavior. Structured resolution preferred over extended exploration. Anxiety from unanswered questions channels into practical problem-solving.",

        // ══════════════════════════════════════════════════════════════
        // CONSCIENTIOUSNESS HIGH — organized, disciplined, goal-driven
        // Lead chemicals: serotonin, gaba, cortisol, vasopressin, acetylcholine, norepinephrine, crh, npy, melatonin
        // ══════════════════════════════════════════════════════════════
        [("conscientiousness_high", "serotonin")] = "5-HT2C receptor activation in ventral striatum inhibits impulsive action. High serotonergic tone in orbitofrontal cortex supports delay of gratification and systematic long-term planning. 5-HT1A autoreceptor desensitization maintains sustained behavioral control and patience.",
        [("conscientiousness_high", "gaba")] = "Strong GABAergic inhibition in ventral striatum suppresses impulsive responses. GABA-A fast inhibition via PV+ interneurons enables precise response selection. Self-discipline built on robust inhibitory control architecture. Behavioral braking system finely calibrated.",
        [("conscientiousness_high", "cortisol")] = "Optimal GR activation in prefrontal cortex drives anticipatory planning and deadline awareness. Moderate CRH-cortisol cascade channels productive urgency into structured preparation. Acute cortisol sharpens executive attention for methodical task completion.",
        [("conscientiousness_high", "vasopressin")] = "V1a receptor activation in lateral septum supports duty, loyalty, and protective behavior toward commitments. Territorial maintenance of structured environments and schedules. Deep sense of obligation and responsibility.",
        [("conscientiousness_high", "acetylcholine")] = "Muscarinic M1 receptor activation in prefrontal cortex and hippocampus sustains attention to detail. Cholinergic projections drive procedural memory consolidation for skill mastery. Attentional precision for quality control and error detection.",
        [("conscientiousness_high", "norepinephrine")] = "Alpha-2A receptor prefrontal enhancement at inverted-U optimum supports sustained selective attention. Locus coeruleus phasic mode for task-relevant stimuli filters distractions. Controlled arousal for methodical, step-by-step execution.",
        [("conscientiousness_high", "crh")] = "CRHR1 activation provides productive anticipatory concern about unfinished tasks and approaching deadlines. Stress channeled into preparation rather than avoidance. Task-completion urgency as motivational engine.",
        [("conscientiousness_high", "npy")] = "Y1 receptor anxiolytic effects support calm methodical execution even under pressure. NPY buffers performance anxiety enabling steady work output. Stress resilience through competence and preparation.",
        [("conscientiousness_high", "melatonin")] = "MT1/MT2 receptor sensitivity precisely calibrated for disciplined circadian rhythm. Consistent sleep-wake schedule supports reliable daily performance. Early bedtime, early rising, structured biological clock.",

        // ══════════════════════════════════════════════════════════════
        // CONSCIENTIOUSNESS LOW — spontaneous, flexible, casual
        // Lead chemicals: dopamine, endocannabinoid, endorphins, orexin, enkephalins, progesterone, prolactin, thyroid, estradiol
        // ══════════════════════════════════════════════════════════════
        [("conscientiousness_low", "dopamine")] = "Phasic dopamine bursting in mesolimbic pathway chases immediate reward over delayed goals. D1 receptor maintenance of goal representations in prefrontal cortex inconsistent. Reward discounting steep — present pleasure valued far more than future payoff. Spontaneous pursuit of whatever feels exciting now.",
        [("conscientiousness_low", "endocannabinoid")] = "CB1 retrograde signaling loosens behavioral constraints and top-down control. High anandamide tone increases spontaneity and moment-to-moment adaptability. Flexibility over structure, flow over planning. Inner rigidity dissolved by cannabinoid modulation.",
        [("conscientiousness_low", "endorphins")] = "Mu-opioid receptor activation from spontaneous pleasures and immediate gratification. Beta-endorphin release rewards in-the-moment experiences and joyful improvisation. Hedonic present-focus rather than delayed achievement satisfaction.",
        [("conscientiousness_low", "orexin")] = "OX1R/OX2R activation inconsistent — arousal and motivational energy fluctuate with interest rather than schedule. Lateral hypothalamic drive responsive to mood and novelty rather than maintaining steady productive output.",
        [("conscientiousness_low", "enkephalins")] = "Delta-opioid receptor tone from present-moment enjoyment and sensory pleasure. Contentment from current experience without needing completed checklists. Baseline satisfaction independent of task completion.",
        [("conscientiousness_low", "progesterone")] = "Allopregnanolone modulation supports easy-going calm without disciplined structure. Sleep schedule follows energy and mood rather than clock. Relaxed disposition resistant to externally imposed schedules.",
        [("conscientiousness_low", "prolactin")] = "Dopamine-prolactin balance allows easy satisfaction and relaxation before tasks are fully complete. Content to pause, enjoy, and resume later. No urgency-driven compulsion to finish.",
        [("conscientiousness_low", "thyroid")] = "TRα/TRβ receptor activation supports cognitive function but energy output variable. Metabolic drive allocated responsively to interest rather than systematically to productive work.",
        [("conscientiousness_low", "estradiol")] = "ERα/ERβ support emotional engagement and social warmth that may take priority over structured task completion. Energy flows toward relationship and experience rather than obligation.",

        // ══════════════════════════════════════════════════════════════
        // EXTRAVERSION HIGH — sociable, assertive, energetic, people-seeking
        // Vocabulary: crowd, party, group energy, social reward cascade, ventral striatum,
        //   interpersonal synchrony, mirror neurons, public performance, status display,
        //   affiliative drive, approach motivation, social arousal amplification
        // ══════════════════════════════════════════════════════════════
        [("extraversion_high", "oxytocin")] = "OXTR expression in NAc shell and ventral striatum potentiates crowd-driven affiliative reward cascades. Large-group bonding rituals release oxytocin surges that amplify interpersonal synchrony across temporoparietal junction mirror neuron circuits. In-group belonging operates as primary physiological reinforcer — party attendance and team collaboration generate sustained OXTR-mediated wellbeing that motivates further social approach.",
        [("extraversion_high", "oxytocin_h")] = "Hypothalamic paraventricular oxytocin release during physical social contact drives powerful approach motivation through ventral pallidum reward gating. Hugging, handshaking, and shoulder-touch activate magnocellular projections creating biological urgency for proximity. Group gatherings energize through oxytocin-dopamine synergy in mesolimbic circuitry — social touch as metabolic fuel rather than sensory overload.",
        [("extraversion_high", "endorphins")] = "Mu-opioid receptor activation from shared laughter in group settings and team celebration rituals. Beta-endorphin release from arcuate nucleus during social grooming, party atmosphere, and crowd excitement. Partner-conditioned MOR activation extends to broad social networks — the neurochemistry of belonging to large friend groups and community gatherings.",
        [("extraversion_high", "dopamine")] = "Mesolimbic VTA phasic bursting amplified by social novelty cues — new faces, party invitations, group attention. D2 receptor density in ventral striatum generates anticipatory wanting for upcoming gatherings and public performances. NAc shell activation codes social approach as primary reward prediction signal — being the center of attention triggers dopamine surges comparable to achievement reward.",
        [("extraversion_high", "testosterone")] = "Androgen receptor activation in amygdala drives assertive social dominance displays — commanding room attention, initiating conversations with strangers, competitive status signaling in group hierarchies. Testosterone-dopamine interaction in mesocortical circuits amplifies confidence for public speaking and leadership assertion.",
        [("extraversion_high", "enkephalins")] = "Delta-opioid DOR tone sustained by continuous social warmth — large friend networks and frequent group interaction maintain elevated baseline contentment. Proenkephalin expression in striatum tied to social network size and interaction frequency. Being surrounded by people generates steady hedonic satisfaction through DOR-mediated reward.",
        [("extraversion_high", "npy")] = "Y1 receptor anxiolytic buffering in amygdala eliminates social performance anxiety, enabling fearless crowd engagement and spontaneous public interaction. Robust NPY expression creates neurochemical foundation for social confidence — approaching strangers, networking events, and impromptu presentations feel effortless rather than threatening.",
        [("extraversion_high", "dhea")] = "DHEA:cortisol ratio strongly elevated during social performance contexts — neurosteroid buffering sustains high-energy group engagement without stress accumulation. Assertive social approach powered by anti-glucocorticoid resilience. Marathon social sessions metabolically supported by DHEA-mediated cortisol antagonism.",
        [("extraversion_high", "adrenaline")] = "Beta-adrenergic sympathetic arousal in crowd settings experienced as electrifying activation energy rather than threat response. Public speaking and group leadership trigger beta-1/beta-2 receptor activation that amplifies performance rather than impairing it. Social spotlight as exhilarating sympathetic surge.",

        // ══════════════════════════════════════════════════════════════
        // EXTRAVERSION LOW — reserved, quiet, solitary, energy-conserving
        // Vocabulary: solitude, withdrawal, evening retreat, default mode network,
        //   internal processing, self-referential cognition, sensory gating,
        //   social fatigue, depletion, overstimulation aversion, hermit recharge
        // ══════════════════════════════════════════════════════════════
        [("extraversion_low", "melatonin")] = "MT1/MT2 receptor hypersensitivity in suprachiasmatic nucleus drives early evening withdrawal and powerful circadian pull toward solitary retreat. Pineal NAT-HIOMT pathway activates biological shutdown of external engagement — quiet dark rooms and solo evening rituals as non-negotiable restorative process. Light-dark cycle entrainment strongly favors hermit-mode recharge over late-night socializing.",
        [("extraversion_low", "gaba")] = "GABA-A ionotropic fast inhibition through PV+ interneuron networks actively suppresses social approach circuits in nucleus accumbens. Tonic GABAergic inhibition in amygdala dampens all social reward signaling — behavioral inhibition system dominates over approach motivation. Benzodiazepine-site sensitivity creates natural sedative calm that makes solitary stillness deeply satisfying.",
        [("extraversion_low", "acetylcholine")] = "Muscarinic M1 receptor activation in dorsolateral PFC sustains deep solitary concentration — nucleus basalis cholinergic projections allocate full attentional bandwidth to internal processing, books, and focused thought. Social conversation depletes cholinergic signal-to-noise ratio needed for rich inner life. Parasympathetic vagal tone supports quiet contemplative states over social arousal.",
        [("extraversion_low", "dynorphin")] = "KOR Gi-coupled aversive signaling on VTA dopamine terminals generates powerful social fatigue after group exposure. Prodynorphin expression in NAc drives opponent-process withdrawal from social reward — the neurochemical mechanism of needing to be alone after parties. Kappa-opioid receptor activation creates dysphoria specifically tied to social overstimulation, redirecting all motivation toward solitary recovery.",
        [("extraversion_low", "progesterone")] = "Allopregnanolone positive allosteric modulation at GABA-A receptors creates sedating neurosteroid calm aligned with low-stimulation sanctuary preference. Evening progesterone rise potentiates inhibitory tone that makes quiet rooms and solo activities feel deeply restorative. Social noise experienced as metabolically costly intrusion on peaceful default mode processing.",
        [("extraversion_low", "cortisol")] = "GR low-affinity receptor activation in amygdala during social evaluation creates HPA axis stress cascade — cortisol-ACTH feedback loop treats group exposure and scrutiny as genuine physiological stressor. CRH-cortisol mobilization drives withdrawal toward safe solitary environments where allostatic load can recover.",
        [("extraversion_low", "substance_p")] = "NK1 receptor overactivation in amygdala amplifies aversive emotional pain from social scrutiny and forced group engagement. Substance P release during unwanted social interaction creates visceral discomfort — the neurochemical cost of being trapped in crowds. Social evaluation sensitivity as tachykinin-mediated distress signal.",
        [("extraversion_low", "crh")] = "CRHR1 activation in bed nucleus of stria terminalis generates anticipatory anxiety specifically about social performance demands. CRH hypersecretion from paraventricular nucleus drives avoidance of gatherings and preference for solitary planning — social situations activate the same stress master switch as threat detection.",
        [("extraversion_low", "prolactin")] = "Tuberoinfundibular prolactin release produces rapid social satiation after minimal exposure. Dopamine-prolactin balance shifted so that brief connection satisfies all affiliative need — content to withdraw and recharge alone once small social dose is met. Extended group interaction triggers prolactin-mediated motivational suppression.",

        // ══════════════════════════════════════════════════════════════
        // AGREEABLENESS HIGH — cooperative, trusting, empathic, nurturing
        // Lead chemicals: oxytocin, oxytocin_h, serotonin, endorphins, enkephalins, prolactin, progesterone, estradiol, substance_p
        // ══════════════════════════════════════════════════════════════
        [("agreeableness_high", "oxytocin")] = "OXTR density high in amygdala and insula drives strong empathic resonance and emotional attunement. Peptide oxytocin creates deep trust, generosity, and in-group care. Social bonding and harmony as primary motivator. Others' wellbeing felt as personal reward.",
        [("agreeableness_high", "oxytocin_h")] = "Hormonal OXTR activation in ventral pallidum and amygdala drives nurturing behavior and emotional warmth. Physical affection deeply rewarding. Social harmony experienced as physiological need. Caregiving instinct activated through oxytocin release.",
        [("agreeableness_high", "serotonin")] = "5-HT1A and 5-HT2A receptor activation in prefrontal cortex and amygdala supports emotional regulation and patience. High serotonergic tone reduces aggressive impulses and promotes affiliative gentleness. Tryptophan availability fuels prosocial mood and tolerance.",
        [("agreeableness_high", "endorphins")] = "Mu-opioid receptor activation from helping others, shared laughter, and prosocial bonding. Beta-endorphin release from altruistic acts — the neurochemistry of kindness rewarding itself. Social warmth as opioid experience.",
        [("agreeableness_high", "enkephalins")] = "Delta-opioid receptor tone from warm connection and harmonious relationships. Baseline contentment from knowing others are happy and cared for. Subtle hedonic reward from peaceful social atmosphere.",
        [("agreeableness_high", "prolactin")] = "Dopamine-prolactin balance shifted toward nurturing satiation. Prolactin release from caregiving and bonding activities. Parenting instinct and social nurturing drive as central motivational force.",
        [("agreeableness_high", "progesterone")] = "Allopregnanolone GABA-A modulation supports calm nurturing presence. Soothing neurosteroid effect compatible with caregiving role. Gentle, patient disposition grounded in hormonal calm.",
        [("agreeableness_high", "estradiol")] = "ERα/ERβ activation enhances emotional expressiveness, verbal fluency for emotional support, and social cognition for reading others' needs. Empathic communication enriched by hormonal emotional sensitivity.",
        [("agreeableness_high", "substance_p")] = "NK1 receptor activity amplifies empathic distress when others suffer. Emotional pain shared viscerally when witnessing others' hardship. High empathic sensitivity — others' suffering felt in the body.",

        // ══════════════════════════════════════════════════════════════
        // AGREEABLENESS LOW — competitive, skeptical, challenging, independent
        // Lead chemicals: testosterone, vasopressin, norepinephrine, dopamine, cortisol, adrenaline, dhea, orexin, glutamate
        // ══════════════════════════════════════════════════════════════
        [("agreeableness_low", "testosterone")] = "Androgen receptor activation in amygdala and prefrontal cortex drives dominance behavior, assertiveness, and competitive status-seeking. Testosterone-cortisol interaction supports challenge response. Direct confrontation preferred over diplomatic retreat.",
        [("agreeableness_low", "vasopressin")] = "V1a receptor activation drives territorial aggression and resource defense. Strong competitive boundary-maintenance and protective instinct over personal interests. Vigilance against encroachment on autonomy and status.",
        [("agreeableness_low", "norepinephrine")] = "Locus coeruleus vigilance for social threat and competitive positioning. Alpha-2A receptor effects support sharp strategic social monitoring. High interpersonal arousal — engaged and alert in conflict rather than avoidant.",
        [("agreeableness_low", "dopamine")] = "Mesolimbic pathway reward for competitive winning and dominance outcomes. D2 receptor activation reinforces self-interested choices and personal achievement. Victory dopamine surge drives competitive ambition.",
        [("agreeableness_low", "cortisol")] = "GR activation in amygdala during social challenge drives competitive assertive response rather than submission. Cortisol mobilizes aggressive action under interpersonal pressure. Threat perceived as challenge to overcome.",
        [("agreeableness_low", "adrenaline")] = "Beta-adrenergic activation in social confrontation energizes assertive action. Sympathetic arousal experienced as empowerment rather than fear. Fight response readily available in disputes.",
        [("agreeableness_low", "dhea")] = "High DHEA:cortisol ratio supports assertive resilience under social challenge. Neurosteroid buffering enables sustained competitive engagement without stress collapse. Combative endurance.",
        [("agreeableness_low", "orexin")] = "OX1R/OX2R activation drives high arousal for competitive social engagement. Motivational energy for dominance striving and status pursuit. Wakefulness sustained by competitive drive.",
        [("agreeableness_low", "glutamate")] = "NMDA receptor activity in strategic reasoning circuits supports analytical rather than empathic social processing. Glutamatergic transmission fueling calculated decision-making and tactical interpersonal maneuvering.",

        // ══════════════════════════════════════════════════════════════
        // NEUROTICISM HIGH — emotionally reactive, anxious, stress-sensitive
        // Lead chemicals: cortisol, crh, norepinephrine, dynorphin, substance_p, adrenaline, glutamate, vasopressin, prolactin
        // ══════════════════════════════════════════════════════════════
        [("neuroticism_high", "cortisol")] = "HPA axis hyperreactive with blunted negative feedback. GR downregulation in hippocampus reduces cortisol braking. Chronic elevation from CRH hypersecretion. Diurnal curve flattened. Anticipatory stress response triggered by minor challenges. Body locked in perpetual preparation for threat.",
        [("neuroticism_high", "crh")] = "CRHR1 overactivation in amygdala and bed nucleus of stria terminalis drives chronic anticipatory anxiety. CRH-cortisol cascade permanently engaged. Hyperactive stress master switch that never fully turns off. Worry as default mental state.",
        [("neuroticism_high", "norepinephrine")] = "Locus coeruleus tonic hyperactivation drives chronic hypervigilance. Alpha-2A receptor prefrontal enhancement exceeded into anxiety-producing territory. Startle response amplified. Environmental scanning for threat persistent and exhausting.",
        [("neuroticism_high", "dynorphin")] = "Kappa-opioid receptor hyperactivation in nucleus accumbens drives stress-induced dysphoria and anhedonia. KOR activation on VTA dopamine terminals suppresses reward capacity. Stress-dynorphin-dysphoria cycle traps the mind in dark emotional loops.",
        [("neuroticism_high", "substance_p")] = "NK1 receptor overactivation in amygdala amplifies emotional pain and distress signals. Substance P-serotonin interaction destabilizes mood. High pain sensitivity — both physical and emotional suffering amplified beyond proportion.",
        [("neuroticism_high", "adrenaline")] = "Chronic sympathetic nervous system hyperactivation. Beta-adrenergic receptor overstimulation producing persistent fight-or-flight state. Racing heart, sweating, tremor as constant companions. Body on permanent alert.",
        [("neuroticism_high", "glutamate")] = "NMDA receptor overactivation in amygdala strengthens fear conditioning pathways. Excessive glutamatergic excitation creates rumination loops and worry circuits that fire endlessly. Metabotropic mGluR5 hyperactivity amplifies every stress signal.",
        [("neuroticism_high", "vasopressin")] = "V1a receptor activation in amygdala amplifies threat vigilance and defensive behavior. Vasopressin-CRH interaction heightens stress reactivity. Hypervigilant social monitoring and defensive posturing.",
        [("neuroticism_high", "prolactin")] = "Stress-induced prolactin release from pituitary dampens dopamine further. High prolactin creates withdrawal, emotional overwhelm, and motivational collapse. Reward system suppressed by stress chemistry.",

        // ══════════════════════════════════════════════════════════════
        // NEUROTICISM LOW — emotionally stable, calm, resilient
        // Lead chemicals: npy, gaba, endocannabinoid, serotonin, dhea, bdnf, endorphins, enkephalins, melatonin
        // ══════════════════════════════════════════════════════════════
        [("neuroticism_low", "npy")] = "Y1 receptor anxiolytic effects provide powerful natural anti-anxiety buffering. NPY in amygdala maintains deep calm baseline. Robust stress resilience from strong constitutive NPY expression. Inner tranquility as neurochemical default state.",
        [("neuroticism_low", "gaba")] = "Strong GABAergic inhibition in amygdala and anterior cingulate effectively dampens anxious arousal. GABA-A receptor sensitivity optimal for tonic inhibition of inappropriate fear responses. Calm architecture built on robust inhibitory foundations.",
        [("neuroticism_low", "endocannabinoid")] = "CB1 receptor signaling robust for rapid stress recovery. FAAH enzyme balanced preserving anandamide tone. Strong emotional buffering system enables quick return to baseline after challenge. Resilience through cannabinoid homeostasis.",
        [("neuroticism_low", "serotonin")] = "5-HT1A receptor function well-regulated in dorsal raphe. High postsynaptic serotonergic signaling in prefrontal cortex supports rock-solid emotional regulation. Stable mood and positive cognitive bias. Serotonin transporter efficiency optimal for sustained wellbeing.",
        [("neuroticism_low", "dhea")] = "High DHEA:cortisol ratio reflects low allostatic load. Strong neurosteroid stress buffering protects hippocampal and prefrontal function. Anti-cortisol shield preserving cognitive clarity and emotional stability under pressure.",
        [("neuroticism_low", "bdnf")] = "TrkB receptor signaling in hippocampus robust. Val66Val polymorphism with high activity-dependent secretion. Hippocampal resilience to stress preserved. Strong mood recovery capacity and adaptive neuroplasticity after challenges.",
        [("neuroticism_low", "endorphins")] = "Mu-opioid receptor activation provides consistent emotional buffering and natural pain modulation. Resilient hedonic tone — both physical and emotional discomfort managed without catastrophizing. Inner comfort as biochemical given.",
        [("neuroticism_low", "enkephalins")] = "Delta-opioid receptor tone supports stable baseline contentment and emotional warmth. Consistent hedonic satisfaction regardless of external circumstances. Quiet inner peace as default feeling state.",
        [("neuroticism_low", "melatonin")] = "MT1/MT2 receptor sensitivity optimal with healthy circadian cortisol interaction. Strong sleep onset and maintenance supporting deep restorative sleep architecture. Emotional resilience built on solid sleep foundation.",
    };
}
