// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Diag
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "program_id")]
        public ulong ProgramId;
        [DataMember(Name = "kind")]
        public string Kind;
        [DataMember(Name = "name")]
        public string? Name;
        [DataMember(Name = "expr")]
        public string Expr;
        [DataMember(Name = "detail")]
        public System.Collections.Generic.List<Kv> Detail;

        public Diag(
            ulong Id,
            ulong ProgramId,
            string Kind,
            string? Name,
            string Expr,
            System.Collections.Generic.List<Kv> Detail
        )
        {
            this.Id = Id;
            this.ProgramId = ProgramId;
            this.Kind = Kind;
            this.Name = Name;
            this.Expr = Expr;
            this.Detail = Detail;
        }

        public Diag()
        {
            this.Kind = "";
            this.Expr = "";
            this.Detail = new();
        }
    }
}
