// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class GateSpec
    {
        [DataMember(Name = "node_code")]
        public string NodeCode;
        [DataMember(Name = "region")]
        public string Region;
        [DataMember(Name = "threshold")]
        public string Threshold;

        public GateSpec(
            string NodeCode,
            string Region,
            string Threshold
        )
        {
            this.NodeCode = NodeCode;
            this.Region = Region;
            this.Threshold = Threshold;
        }

        public GateSpec()
        {
            this.NodeCode = "";
            this.Region = "";
            this.Threshold = "";
        }
    }
}
