// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class MetaTarget
    {
        [DataMember(Name = "code")]
        public string Code;
        [DataMember(Name = "region")]
        public string Region;
        [DataMember(Name = "property")]
        public string Property;
        [DataMember(Name = "program")]
        public string Program;
        [DataMember(Name = "reversible")]
        public string? Reversible;
        [DataMember(Name = "unlocks_with")]
        public string? UnlocksWith;
        [DataMember(Name = "pull")]
        public string? Pull;

        public MetaTarget(
            string Code,
            string Region,
            string Property,
            string Program,
            string? Reversible,
            string? UnlocksWith,
            string? Pull
        )
        {
            this.Code = Code;
            this.Region = Region;
            this.Property = Property;
            this.Program = Program;
            this.Reversible = Reversible;
            this.UnlocksWith = UnlocksWith;
            this.Pull = Pull;
        }

        public MetaTarget()
        {
            this.Code = "";
            this.Region = "";
            this.Property = "";
            this.Program = "";
        }
    }
}
