// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class NodeState
    {
        [DataMember(Name = "sym")]
        public string Sym;
        [DataMember(Name = "val")]
        public float? Val;
        [DataMember(Name = "delta_sign")]
        public string? DeltaSign;
        [DataMember(Name = "delta_val")]
        public float? DeltaVal;

        public NodeState(
            string Sym,
            float? Val,
            string? DeltaSign,
            float? DeltaVal
        )
        {
            this.Sym = Sym;
            this.Val = Val;
            this.DeltaSign = DeltaSign;
            this.DeltaVal = DeltaVal;
        }

        public NodeState()
        {
            this.Sym = "";
        }
    }
}
