// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Perturbation
    {
        [DataMember(Name = "target_code")]
        public string TargetCode;
        [DataMember(Name = "target_region")]
        public string TargetRegion;
        [DataMember(Name = "action")]
        public string Action;
        [DataMember(Name = "value")]
        public float? Value;

        public Perturbation(
            string TargetCode,
            string TargetRegion,
            string Action,
            float? Value
        )
        {
            this.TargetCode = TargetCode;
            this.TargetRegion = TargetRegion;
            this.Action = Action;
            this.Value = Value;
        }

        public Perturbation()
        {
            this.TargetCode = "";
            this.TargetRegion = "";
            this.Action = "";
        }
    }
}
