// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Program
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "patient_id")]
        public string PatientId;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "phase")]
        public string? Phase;
        [DataMember(Name = "domains")]
        public System.Collections.Generic.List<string> Domains;
        [DataMember(Name = "tick")]
        public uint Tick;
        [DataMember(Name = "raw_base")]
        public string? RawBase;
        [DataMember(Name = "raw_plasticity")]
        public string? RawPlasticity;
        [DataMember(Name = "raw_meta")]
        public string? RawMeta;
        [DataMember(Name = "raw_convergence")]
        public string? RawConvergence;
        [DataMember(Name = "created_at")]
        public SpacetimeDB.Timestamp CreatedAt;

        public Program(
            ulong Id,
            string PatientId,
            string Name,
            string? Phase,
            System.Collections.Generic.List<string> Domains,
            uint Tick,
            string? RawBase,
            string? RawPlasticity,
            string? RawMeta,
            string? RawConvergence,
            SpacetimeDB.Timestamp CreatedAt
        )
        {
            this.Id = Id;
            this.PatientId = PatientId;
            this.Name = Name;
            this.Phase = Phase;
            this.Domains = Domains;
            this.Tick = Tick;
            this.RawBase = RawBase;
            this.RawPlasticity = RawPlasticity;
            this.RawMeta = RawMeta;
            this.RawConvergence = RawConvergence;
            this.CreatedAt = CreatedAt;
        }

        public Program()
        {
            this.PatientId = "";
            this.Name = "";
            this.Domains = new();
        }
    }
}
