// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PropChange
    {
        [DataMember(Name = "property")]
        public string Property;
        [DataMember(Name = "before")]
        public string Before;
        [DataMember(Name = "after")]
        public string After;

        public PropChange(
            string Property,
            string Before,
            string After
        )
        {
            this.Property = Property;
            this.Before = Before;
            this.After = After;
        }

        public PropChange()
        {
            this.Property = "";
            this.Before = "";
            this.After = "";
        }
    }
}
