// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Snapshot
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "program_id")]
        public ulong ProgramId;
        [DataMember(Name = "tick")]
        public uint Tick;
        [DataMember(Name = "label")]
        public string? Label;
        [DataMember(Name = "created_at")]
        public SpacetimeDB.Timestamp CreatedAt;

        public Snapshot(
            ulong Id,
            ulong ProgramId,
            uint Tick,
            string? Label,
            SpacetimeDB.Timestamp CreatedAt
        )
        {
            this.Id = Id;
            this.ProgramId = ProgramId;
            this.Tick = Tick;
            this.Label = Label;
            this.CreatedAt = CreatedAt;
        }

        public Snapshot()
        {
        }
    }
}
