// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class SnapshotDiff
    {
        [DataMember(Name = "kind")]
        public string Kind;
        [DataMember(Name = "entity_id")]
        public ulong EntityId;
        [DataMember(Name = "field")]
        public string Field;
        [DataMember(Name = "old_val")]
        public string OldVal;
        [DataMember(Name = "new_val")]
        public string NewVal;

        public SnapshotDiff(
            string Kind,
            ulong EntityId,
            string Field,
            string OldVal,
            string NewVal
        )
        {
            this.Kind = Kind;
            this.EntityId = EntityId;
            this.Field = Field;
            this.OldVal = OldVal;
            this.NewVal = NewVal;
        }

        public SnapshotDiff()
        {
            this.Kind = "";
            this.Field = "";
            this.OldVal = "";
            this.NewVal = "";
        }
    }
}
