// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class SnapshotNode
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "snapshot_id")]
        public ulong SnapshotId;
        [DataMember(Name = "node_id")]
        public ulong NodeId;
        [DataMember(Name = "code")]
        public string Code;
        [DataMember(Name = "region")]
        public string? Region;
        [DataMember(Name = "state_sym")]
        public string? StateSym;
        [DataMember(Name = "state_val")]
        public float? StateVal;

        public SnapshotNode(
            ulong Id,
            ulong SnapshotId,
            ulong NodeId,
            string Code,
            string? Region,
            string? StateSym,
            float? StateVal
        )
        {
            this.Id = Id;
            this.SnapshotId = SnapshotId;
            this.NodeId = NodeId;
            this.Code = Code;
            this.Region = Region;
            this.StateSym = StateSym;
            this.StateVal = StateVal;
        }

        public SnapshotNode()
        {
            this.Code = "";
        }
    }
}
