// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class TauAccumulator
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "sim_run_id")]
        public ulong SimRunId;
        [DataMember(Name = "trigger_id")]
        public ulong TriggerId;
        [DataMember(Name = "trigger_kind")]
        public string TriggerKind;
        [DataMember(Name = "accumulated")]
        public float Accumulated;
        [DataMember(Name = "tau_target")]
        public float TauTarget;

        public TauAccumulator(
            ulong Id,
            ulong SimRunId,
            ulong TriggerId,
            string TriggerKind,
            float Accumulated,
            float TauTarget
        )
        {
            this.Id = Id;
            this.SimRunId = SimRunId;
            this.TriggerId = TriggerId;
            this.TriggerKind = TriggerKind;
            this.Accumulated = Accumulated;
            this.TauTarget = TauTarget;
        }

        public TauAccumulator()
        {
            this.TriggerKind = "";
        }
    }
}
