apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jabn-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
spec:
  ingressClassName: nginx
  rules:
  - host: chat.jabn.no
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: open-webui
            port:
              number: 80
  - host: openclaw.jabn.no
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: openclaw
            port:
              number: 18789
  - host: mcp.jabn.no
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mcpserver
            port:
              number: 80
