<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>NeuroGateway.Service</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NeuroGateway.AgentFramework\NeuroGateway.AgentFramework.csproj" />
    <ProjectReference Include="..\NeuroGateway.AnalysisFramework\NeuroGateway.AnalysisFramework.csproj" />
    <ProjectReference Include="..\NeuroGateway.Repository\NeuroGateway.Repository.csproj" />
    <ProjectReference Include="..\NeuroGateway.Models\NeuroGateway.Models.csproj" />
    <ProjectReference Include="..\NeuroGateway.Utils\NeuroGateway.Utils.csproj" />
  </ItemGroup>

</Project>
