// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ConvVector
    {
        [DataMember(Name = "source")]
        public string Source;
        [DataMember(Name = "state")]
        public string State;
        [DataMember(Name = "detail")]
        public string? Detail;

        public ConvVector(
            string Source,
            string State,
            string? Detail
        )
        {
            this.Source = Source;
            this.State = State;
            this.Detail = Detail;
        }

        public ConvVector()
        {
            this.Source = "";
            this.State = "";
        }
    }
}
