// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Edge
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "program_id")]
        public ulong ProgramId;
        [DataMember(Name = "source_id")]
        public ulong SourceId;
        [DataMember(Name = "target_id")]
        public ulong TargetId;
        [DataMember(Name = "rank_tag")]
        public string RankTag;
        [DataMember(Name = "edge_type")]
        public string? EdgeType;
        [DataMember(Name = "coeff")]
        public float Coeff;
        [DataMember(Name = "gate")]
        public GateSpec? Gate;
        [DataMember(Name = "protocol")]
        public ProtocolSpec? Protocol;
        [DataMember(Name = "proto_label")]
        public string? ProtoLabel;
        [DataMember(Name = "chain")]
        public string? Chain;
        [DataMember(Name = "chain_pos")]
        public uint? ChainPos;
        [DataMember(Name = "ring_id")]
        public string? RingId;

        public Edge(
            ulong Id,
            ulong ProgramId,
            ulong SourceId,
            ulong TargetId,
            string RankTag,
            string? EdgeType,
            float Coeff,
            GateSpec? Gate,
            ProtocolSpec? Protocol,
            string? ProtoLabel,
            string? Chain,
            uint? ChainPos,
            string? RingId
        )
        {
            this.Id = Id;
            this.ProgramId = ProgramId;
            this.SourceId = SourceId;
            this.TargetId = TargetId;
            this.RankTag = RankTag;
            this.EdgeType = EdgeType;
            this.Coeff = Coeff;
            this.Gate = Gate;
            this.Protocol = Protocol;
            this.ProtoLabel = ProtoLabel;
            this.Chain = Chain;
            this.ChainPos = ChainPos;
            this.RingId = RingId;
        }

        public Edge()
        {
            this.RankTag = "";
        }
    }
}
