// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class IntegInput
    {
        [DataMember(Name = "code")]
        public string Code;
        [DataMember(Name = "region")]
        public string Region;
        [DataMember(Name = "weight")]
        public float Weight;
        [DataMember(Name = "w_type")]
        public string WType;

        public IntegInput(
            string Code,
            string Region,
            float Weight,
            string WType
        )
        {
            this.Code = Code;
            this.Region = Region;
            this.Weight = Weight;
            this.WType = WType;
        }

        public IntegInput()
        {
            this.Code = "";
            this.Region = "";
            this.WType = "";
        }
    }
}
