// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Integration
    {
        [DataMember(Name = "inputs")]
        public System.Collections.Generic.List<IntegInput> Inputs;
        [DataMember(Name = "output")]
        public IntegOutput Output;

        public Integration(
            System.Collections.Generic.List<IntegInput> Inputs,
            IntegOutput Output
        )
        {
            this.Inputs = Inputs;
            this.Output = Output;
        }

        public Integration()
        {
            this.Inputs = new();
            this.Output = new();
        }
    }
}
