// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Node
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "program_id")]
        public ulong ProgramId;
        [DataMember(Name = "code")]
        public string Code;
        [DataMember(Name = "kind")]
        public string Kind;
        [DataMember(Name = "region")]
        public string? Region;
        [DataMember(Name = "rank_tag")]
        public string RankTag;
        [DataMember(Name = "state")]
        public NodeState? State;
        [DataMember(Name = "integ")]
        public Integration? Integ;
        [DataMember(Name = "props")]
        public System.Collections.Generic.List<Kv> Props;
        [DataMember(Name = "is_root")]
        public bool IsRoot;
        [DataMember(Name = "terminal")]
        public string? Terminal;

        public Node(
            ulong Id,
            ulong ProgramId,
            string Code,
            string Kind,
            string? Region,
            string RankTag,
            NodeState? State,
            Integration? Integ,
            System.Collections.Generic.List<Kv> Props,
            bool IsRoot,
            string? Terminal
        )
        {
            this.Id = Id;
            this.ProgramId = ProgramId;
            this.Code = Code;
            this.Kind = Kind;
            this.Region = Region;
            this.RankTag = RankTag;
            this.State = State;
            this.Integ = Integ;
            this.Props = Props;
            this.IsRoot = IsRoot;
            this.Terminal = Terminal;
        }

        public Node()
        {
            this.Code = "";
            this.Kind = "";
            this.RankTag = "";
            this.Props = new();
        }
    }
}
