// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class SimRun
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "program_id")]
        public ulong ProgramId;
        [DataMember(Name = "max_ticks")]
        public uint MaxTicks;
        [DataMember(Name = "perturbations")]
        public System.Collections.Generic.List<Perturbation> Perturbations;
        [DataMember(Name = "status")]
        public string Status;
        [DataMember(Name = "final_tick")]
        public uint FinalTick;
        [DataMember(Name = "started_at")]
        public SpacetimeDB.Timestamp StartedAt;

        public SimRun(
            ulong Id,
            ulong ProgramId,
            uint MaxTicks,
            System.Collections.Generic.List<Perturbation> Perturbations,
            string Status,
            uint FinalTick,
            SpacetimeDB.Timestamp StartedAt
        )
        {
            this.Id = Id;
            this.ProgramId = ProgramId;
            this.MaxTicks = MaxTicks;
            this.Perturbations = Perturbations;
            this.Status = Status;
            this.FinalTick = FinalTick;
            this.StartedAt = StartedAt;
        }

        public SimRun()
        {
            this.Perturbations = new();
            this.Status = "";
        }
    }
}
