// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Tensor
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "program_id")]
        public ulong ProgramId;
        [DataMember(Name = "conditions")]
        public System.Collections.Generic.List<TensorCond> Conditions;
        [DataMember(Name = "logic")]
        public string Logic;
        [DataMember(Name = "effect")]
        public TensorEffect Effect;
        [DataMember(Name = "label")]
        public string? Label;

        public Tensor(
            ulong Id,
            ulong ProgramId,
            System.Collections.Generic.List<TensorCond> Conditions,
            string Logic,
            TensorEffect Effect,
            string? Label
        )
        {
            this.Id = Id;
            this.ProgramId = ProgramId;
            this.Conditions = Conditions;
            this.Logic = Logic;
            this.Effect = Effect;
            this.Label = Label;
        }

        public Tensor()
        {
            this.Conditions = new();
            this.Logic = "";
            this.Effect = new();
        }
    }
}
