// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class TensorCond
    {
        [DataMember(Name = "code")]
        public string Code;
        [DataMember(Name = "region")]
        public string Region;
        [DataMember(Name = "state")]
        public string State;
        [DataMember(Name = "negated")]
        public bool Negated;

        public TensorCond(
            string Code,
            string Region,
            string State,
            bool Negated
        )
        {
            this.Code = Code;
            this.Region = Region;
            this.State = State;
            this.Negated = Negated;
        }

        public TensorCond()
        {
            this.Code = "";
            this.Region = "";
            this.State = "";
        }
    }
}
