// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AddNodeHandler(ReducerEventContext ctx, ulong programId, string code, string kind, string? region, string rankTag, SpacetimeDB.Types.NodeState? state, SpacetimeDB.Types.Integration? integ, System.Collections.Generic.List<SpacetimeDB.Types.Kv> props, bool isRoot, string? terminal);
        public event AddNodeHandler? OnAddNode;

        public void AddNode(ulong programId, string code, string kind, string? region, string rankTag, SpacetimeDB.Types.NodeState? state, SpacetimeDB.Types.Integration? integ, System.Collections.Generic.List<SpacetimeDB.Types.Kv> props, bool isRoot, string? terminal)
        {
            conn.InternalCallReducer(new Reducer.AddNode(programId, code, kind, region, rankTag, state, integ, props, isRoot, terminal));
        }

        public bool InvokeAddNode(ReducerEventContext ctx, Reducer.AddNode args)
        {
            if (OnAddNode == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAddNode(
                ctx,
                args.ProgramId,
                args.Code,
                args.Kind,
                args.Region,
                args.RankTag,
                args.State,
                args.Integ,
                args.Props,
                args.IsRoot,
                args.Terminal
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AddNode : Reducer, IReducerArgs
        {
            [DataMember(Name = "program_id")]
            public ulong ProgramId;
            [DataMember(Name = "code")]
            public string Code;
            [DataMember(Name = "kind")]
            public string Kind;
            [DataMember(Name = "region")]
            public string? Region;
            [DataMember(Name = "rank_tag")]
            public string RankTag;
            [DataMember(Name = "state")]
            public NodeState? State;
            [DataMember(Name = "integ")]
            public Integration? Integ;
            [DataMember(Name = "props")]
            public System.Collections.Generic.List<Kv> Props;
            [DataMember(Name = "is_root")]
            public bool IsRoot;
            [DataMember(Name = "terminal")]
            public string? Terminal;

            public AddNode(
                ulong ProgramId,
                string Code,
                string Kind,
                string? Region,
                string RankTag,
                NodeState? State,
                Integration? Integ,
                System.Collections.Generic.List<Kv> Props,
                bool IsRoot,
                string? Terminal
            )
            {
                this.ProgramId = ProgramId;
                this.Code = Code;
                this.Kind = Kind;
                this.Region = Region;
                this.RankTag = RankTag;
                this.State = State;
                this.Integ = Integ;
                this.Props = Props;
                this.IsRoot = IsRoot;
                this.Terminal = Terminal;
            }

            public AddNode()
            {
                this.Code = "";
                this.Kind = "";
                this.RankTag = "";
                this.Props = new();
            }

            string IReducerArgs.ReducerName => "add_node";
        }
    }
}
