// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AddTensorHandler(ReducerEventContext ctx, ulong programId, System.Collections.Generic.List<SpacetimeDB.Types.TensorCond> conditions, string logic, SpacetimeDB.Types.TensorEffect effect, string? label);
        public event AddTensorHandler? OnAddTensor;

        public void AddTensor(ulong programId, System.Collections.Generic.List<SpacetimeDB.Types.TensorCond> conditions, string logic, SpacetimeDB.Types.TensorEffect effect, string? label)
        {
            conn.InternalCallReducer(new Reducer.AddTensor(programId, conditions, logic, effect, label));
        }

        public bool InvokeAddTensor(ReducerEventContext ctx, Reducer.AddTensor args)
        {
            if (OnAddTensor == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAddTensor(
                ctx,
                args.ProgramId,
                args.Conditions,
                args.Logic,
                args.Effect,
                args.Label
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AddTensor : Reducer, IReducerArgs
        {
            [DataMember(Name = "program_id")]
            public ulong ProgramId;
            [DataMember(Name = "conditions")]
            public System.Collections.Generic.List<TensorCond> Conditions;
            [DataMember(Name = "logic")]
            public string Logic;
            [DataMember(Name = "effect")]
            public TensorEffect Effect;
            [DataMember(Name = "label")]
            public string? Label;

            public AddTensor(
                ulong ProgramId,
                System.Collections.Generic.List<TensorCond> Conditions,
                string Logic,
                TensorEffect Effect,
                string? Label
            )
            {
                this.ProgramId = ProgramId;
                this.Conditions = Conditions;
                this.Logic = Logic;
                this.Effect = Effect;
                this.Label = Label;
            }

            public AddTensor()
            {
                this.Conditions = new();
                this.Logic = "";
                this.Effect = new();
            }

            string IReducerArgs.ReducerName => "add_tensor";
        }
    }
}
