// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void IngestBnfHandler(ReducerEventContext ctx, ulong programId, string pipeline, string bnfText);
        public event IngestBnfHandler? OnIngestBnf;

        public void IngestBnf(ulong programId, string pipeline, string bnfText)
        {
            conn.InternalCallReducer(new Reducer.IngestBnf(programId, pipeline, bnfText));
        }

        public bool InvokeIngestBnf(ReducerEventContext ctx, Reducer.IngestBnf args)
        {
            if (OnIngestBnf == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnIngestBnf(
                ctx,
                args.ProgramId,
                args.Pipeline,
                args.BnfText
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class IngestBnf : Reducer, IReducerArgs
        {
            [DataMember(Name = "program_id")]
            public ulong ProgramId;
            [DataMember(Name = "pipeline")]
            public string Pipeline;
            [DataMember(Name = "bnf_text")]
            public string BnfText;

            public IngestBnf(
                ulong ProgramId,
                string Pipeline,
                string BnfText
            )
            {
                this.ProgramId = ProgramId;
                this.Pipeline = Pipeline;
                this.BnfText = BnfText;
            }

            public IngestBnf()
            {
                this.Pipeline = "";
                this.BnfText = "";
            }

            string IReducerArgs.ReducerName => "ingest_bnf";
        }
    }
}
