// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void LintBnfHandler(ReducerEventContext ctx, string pipeline, string bnfText);
        public event LintBnfHandler? OnLintBnf;

        public void LintBnf(string pipeline, string bnfText)
        {
            conn.InternalCallReducer(new Reducer.LintBnf(pipeline, bnfText));
        }

        public bool InvokeLintBnf(ReducerEventContext ctx, Reducer.LintBnf args)
        {
            if (OnLintBnf == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnLintBnf(
                ctx,
                args.Pipeline,
                args.BnfText
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class LintBnf : Reducer, IReducerArgs
        {
            [DataMember(Name = "pipeline")]
            public string Pipeline;
            [DataMember(Name = "bnf_text")]
            public string BnfText;

            public LintBnf(
                string Pipeline,
                string BnfText
            )
            {
                this.Pipeline = Pipeline;
                this.BnfText = BnfText;
            }

            public LintBnf()
            {
                this.Pipeline = "";
                this.BnfText = "";
            }

            string IReducerArgs.ReducerName => "lint_bnf";
        }
    }
}
