// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void LogDeltaFiredHandler(ReducerEventContext ctx, ulong programId, ulong deltaOpId, uint tick);
        public event LogDeltaFiredHandler? OnLogDeltaFired;

        public void LogDeltaFired(ulong programId, ulong deltaOpId, uint tick)
        {
            conn.InternalCallReducer(new Reducer.LogDeltaFired(programId, deltaOpId, tick));
        }

        public bool InvokeLogDeltaFired(ReducerEventContext ctx, Reducer.LogDeltaFired args)
        {
            if (OnLogDeltaFired == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnLogDeltaFired(
                ctx,
                args.ProgramId,
                args.DeltaOpId,
                args.Tick
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class LogDeltaFired : Reducer, IReducerArgs
        {
            [DataMember(Name = "program_id")]
            public ulong ProgramId;
            [DataMember(Name = "delta_op_id")]
            public ulong DeltaOpId;
            [DataMember(Name = "tick")]
            public uint Tick;

            public LogDeltaFired(
                ulong ProgramId,
                ulong DeltaOpId,
                uint Tick
            )
            {
                this.ProgramId = ProgramId;
                this.DeltaOpId = DeltaOpId;
                this.Tick = Tick;
            }

            public LogDeltaFired()
            {
            }

            string IReducerArgs.ReducerName => "log_delta_fired";
        }
    }
}
