// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void QueryEdgesFromHandler(ReducerEventContext ctx, ulong programId, ulong sourceId);
        public event QueryEdgesFromHandler? OnQueryEdgesFrom;

        public void QueryEdgesFrom(ulong programId, ulong sourceId)
        {
            conn.InternalCallReducer(new Reducer.QueryEdgesFrom(programId, sourceId));
        }

        public bool InvokeQueryEdgesFrom(ReducerEventContext ctx, Reducer.QueryEdgesFrom args)
        {
            if (OnQueryEdgesFrom == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnQueryEdgesFrom(
                ctx,
                args.ProgramId,
                args.SourceId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class QueryEdgesFrom : Reducer, IReducerArgs
        {
            [DataMember(Name = "program_id")]
            public ulong ProgramId;
            [DataMember(Name = "source_id")]
            public ulong SourceId;

            public QueryEdgesFrom(
                ulong ProgramId,
                ulong SourceId
            )
            {
                this.ProgramId = ProgramId;
                this.SourceId = SourceId;
            }

            public QueryEdgesFrom()
            {
            }

            string IReducerArgs.ReducerName => "query_edges_from";
        }
    }
}
