// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void QueryNodeHandler(ReducerEventContext ctx, ulong programId, string code, string? region);
        public event QueryNodeHandler? OnQueryNode;

        public void QueryNode(ulong programId, string code, string? region)
        {
            conn.InternalCallReducer(new Reducer.QueryNode(programId, code, region));
        }

        public bool InvokeQueryNode(ReducerEventContext ctx, Reducer.QueryNode args)
        {
            if (OnQueryNode == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnQueryNode(
                ctx,
                args.ProgramId,
                args.Code,
                args.Region
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class QueryNode : Reducer, IReducerArgs
        {
            [DataMember(Name = "program_id")]
            public ulong ProgramId;
            [DataMember(Name = "code")]
            public string Code;
            [DataMember(Name = "region")]
            public string? Region;

            public QueryNode(
                ulong ProgramId,
                string Code,
                string? Region
            )
            {
                this.ProgramId = ProgramId;
                this.Code = Code;
                this.Region = Region;
            }

            public QueryNode()
            {
                this.Code = "";
            }

            string IReducerArgs.ReducerName => "query_node";
        }
    }
}
