// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void QuerySnapshotsHandler(ReducerEventContext ctx, ulong programId);
        public event QuerySnapshotsHandler? OnQuerySnapshots;

        public void QuerySnapshots(ulong programId)
        {
            conn.InternalCallReducer(new Reducer.QuerySnapshots(programId));
        }

        public bool InvokeQuerySnapshots(ReducerEventContext ctx, Reducer.QuerySnapshots args)
        {
            if (OnQuerySnapshots == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnQuerySnapshots(
                ctx,
                args.ProgramId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class QuerySnapshots : Reducer, IReducerArgs
        {
            [DataMember(Name = "program_id")]
            public ulong ProgramId;

            public QuerySnapshots(ulong ProgramId)
            {
                this.ProgramId = ProgramId;
            }

            public QuerySnapshots()
            {
            }

            string IReducerArgs.ReducerName => "query_snapshots";
        }
    }
}
