// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void QueryConvHandler(ReducerEventContext ctx, ulong programId, string? kind);
        public event QueryConvHandler? OnQueryConv;

        public void QueryConv(ulong programId, string? kind)
        {
            conn.InternalCallReducer(new Reducer.QueryConv(programId, kind));
        }

        public bool InvokeQueryConv(ReducerEventContext ctx, Reducer.QueryConv args)
        {
            if (OnQueryConv == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnQueryConv(
                ctx,
                args.ProgramId,
                args.Kind
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class QueryConv : Reducer, IReducerArgs
        {
            [DataMember(Name = "program_id")]
            public ulong ProgramId;
            [DataMember(Name = "kind")]
            public string? Kind;

            public QueryConv(
                ulong ProgramId,
                string? Kind
            )
            {
                this.ProgramId = ProgramId;
                this.Kind = Kind;
            }

            public QueryConv()
            {
            }

            string IReducerArgs.ReducerName => "query_conv";
        }
    }
}
