// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Conv
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "program_id")]
        public ulong ProgramId;
        [DataMember(Name = "kind")]
        public string Kind;
        [DataMember(Name = "signal_code")]
        public string? SignalCode;
        [DataMember(Name = "signal_region")]
        public string? SignalRegion;
        [DataMember(Name = "vectors")]
        public System.Collections.Generic.List<ConvVector>? Vectors;
        [DataMember(Name = "diagnosis")]
        public string? Diagnosis;
        [DataMember(Name = "timeframe")]
        public string? Timeframe;
        [DataMember(Name = "predicted")]
        public string? Predicted;
        [DataMember(Name = "rationale")]
        public string? Rationale;
        [DataMember(Name = "confidence")]
        public string? Confidence;
        [DataMember(Name = "flag_type")]
        public string? FlagType;
        [DataMember(Name = "flag_expr")]
        public string? FlagExpr;
        [DataMember(Name = "risk_name")]
        public string? RiskName;
        [DataMember(Name = "risk_target")]
        public string? RiskTarget;
        [DataMember(Name = "risk_distance")]
        public string? RiskDistance;
        [DataMember(Name = "risk_window")]
        public string? RiskWindow;
        [DataMember(Name = "risk_reversible_before")]
        public string? RiskReversibleBefore;
        [DataMember(Name = "risk_reversible_after")]
        public string? RiskReversibleAfter;
        [DataMember(Name = "monitor_measurement")]
        public string? MonitorMeasurement;
        [DataMember(Name = "monitor_flag_ref")]
        public string? MonitorFlagRef;
        [DataMember(Name = "monitor_note")]
        public string? MonitorNote;

        public Conv(
            ulong Id,
            ulong ProgramId,
            string Kind,
            string? SignalCode,
            string? SignalRegion,
            System.Collections.Generic.List<ConvVector>? Vectors,
            string? Diagnosis,
            string? Timeframe,
            string? Predicted,
            string? Rationale,
            string? Confidence,
            string? FlagType,
            string? FlagExpr,
            string? RiskName,
            string? RiskTarget,
            string? RiskDistance,
            string? RiskWindow,
            string? RiskReversibleBefore,
            string? RiskReversibleAfter,
            string? MonitorMeasurement,
            string? MonitorFlagRef,
            string? MonitorNote
        )
        {
            this.Id = Id;
            this.ProgramId = ProgramId;
            this.Kind = Kind;
            this.SignalCode = SignalCode;
            this.SignalRegion = SignalRegion;
            this.Vectors = Vectors;
            this.Diagnosis = Diagnosis;
            this.Timeframe = Timeframe;
            this.Predicted = Predicted;
            this.Rationale = Rationale;
            this.Confidence = Confidence;
            this.FlagType = FlagType;
            this.FlagExpr = FlagExpr;
            this.RiskName = RiskName;
            this.RiskTarget = RiskTarget;
            this.RiskDistance = RiskDistance;
            this.RiskWindow = RiskWindow;
            this.RiskReversibleBefore = RiskReversibleBefore;
            this.RiskReversibleAfter = RiskReversibleAfter;
            this.MonitorMeasurement = MonitorMeasurement;
            this.MonitorFlagRef = MonitorFlagRef;
            this.MonitorNote = MonitorNote;
        }

        public Conv()
        {
            this.Kind = "";
        }
    }
}
