// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class DeltaLog
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "program_id")]
        public ulong ProgramId;
        [DataMember(Name = "delta_op_id")]
        public ulong DeltaOpId;
        [DataMember(Name = "fired_at_tick")]
        public uint FiredAtTick;
        [DataMember(Name = "fired_at")]
        public SpacetimeDB.Timestamp FiredAt;

        public DeltaLog(
            ulong Id,
            ulong ProgramId,
            ulong DeltaOpId,
            uint FiredAtTick,
            SpacetimeDB.Timestamp FiredAt
        )
        {
            this.Id = Id;
            this.ProgramId = ProgramId;
            this.DeltaOpId = DeltaOpId;
            this.FiredAtTick = FiredAtTick;
            this.FiredAt = FiredAt;
        }

        public DeltaLog()
        {
        }
    }
}
