// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class DeltaOp
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "program_id")]
        public ulong ProgramId;
        [DataMember(Name = "rank_tag")]
        public string RankTag;
        [DataMember(Name = "trigger_code")]
        public string TriggerCode;
        [DataMember(Name = "trigger_region")]
        public string TriggerRegion;
        [DataMember(Name = "trigger_state")]
        public string TriggerState;
        [DataMember(Name = "target_code")]
        public string TargetCode;
        [DataMember(Name = "target_region")]
        public string TargetRegion;
        [DataMember(Name = "change")]
        public PropChange Change;
        [DataMember(Name = "tau")]
        public string Tau;
        [DataMember(Name = "depends")]
        public System.Collections.Generic.List<string> Depends;
        [DataMember(Name = "status")]
        public string? Status;
        [DataMember(Name = "cascade_name")]
        public string? CascadeName;
        [DataMember(Name = "tensor_expr")]
        public string? TensorExpr;

        public DeltaOp(
            ulong Id,
            ulong ProgramId,
            string RankTag,
            string TriggerCode,
            string TriggerRegion,
            string TriggerState,
            string TargetCode,
            string TargetRegion,
            PropChange Change,
            string Tau,
            System.Collections.Generic.List<string> Depends,
            string? Status,
            string? CascadeName,
            string? TensorExpr
        )
        {
            this.Id = Id;
            this.ProgramId = ProgramId;
            this.RankTag = RankTag;
            this.TriggerCode = TriggerCode;
            this.TriggerRegion = TriggerRegion;
            this.TriggerState = TriggerState;
            this.TargetCode = TargetCode;
            this.TargetRegion = TargetRegion;
            this.Change = Change;
            this.Tau = Tau;
            this.Depends = Depends;
            this.Status = Status;
            this.CascadeName = CascadeName;
            this.TensorExpr = TensorExpr;
        }

        public DeltaOp()
        {
            this.RankTag = "";
            this.TriggerCode = "";
            this.TriggerRegion = "";
            this.TriggerState = "";
            this.TargetCode = "";
            this.TargetRegion = "";
            this.Change = new();
            this.Tau = "";
            this.Depends = new();
        }
    }
}
