// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class DiffResult
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "program_id")]
        public ulong ProgramId;
        [DataMember(Name = "snap_a")]
        public ulong SnapA;
        [DataMember(Name = "snap_b")]
        public ulong SnapB;
        [DataMember(Name = "diffs")]
        public System.Collections.Generic.List<SnapshotDiff> Diffs;
        [DataMember(Name = "created_at")]
        public SpacetimeDB.Timestamp CreatedAt;

        public DiffResult(
            ulong Id,
            ulong ProgramId,
            ulong SnapA,
            ulong SnapB,
            System.Collections.Generic.List<SnapshotDiff> Diffs,
            SpacetimeDB.Timestamp CreatedAt
        )
        {
            this.Id = Id;
            this.ProgramId = ProgramId;
            this.SnapA = SnapA;
            this.SnapB = SnapB;
            this.Diffs = Diffs;
            this.CreatedAt = CreatedAt;
        }

        public DiffResult()
        {
            this.Diffs = new();
        }
    }
}
