// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class IntegOutput
    {
        [DataMember(Name = "code")]
        public string Code;
        [DataMember(Name = "region")]
        public string Region;
        [DataMember(Name = "mode")]
        public string Mode;
        [DataMember(Name = "threshold")]
        public string? Threshold;

        public IntegOutput(
            string Code,
            string Region,
            string Mode,
            string? Threshold
        )
        {
            this.Code = Code;
            this.Region = Region;
            this.Mode = Mode;
            this.Threshold = Threshold;
        }

        public IntegOutput()
        {
            this.Code = "";
            this.Region = "";
            this.Mode = "";
        }
    }
}
