// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Kv
    {
        [DataMember(Name = "k")]
        public string K;
        [DataMember(Name = "v")]
        public string V;

        public Kv(
            string K,
            string V
        )
        {
            this.K = K;
            this.V = V;
        }

        public Kv()
        {
            this.K = "";
            this.V = "";
        }
    }
}
