// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class MetaOp
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "program_id")]
        public ulong ProgramId;
        [DataMember(Name = "rank_tag")]
        public string RankTag;
        [DataMember(Name = "window")]
        public MetaWindow Window;
        [DataMember(Name = "target")]
        public MetaTarget Target;

        public MetaOp(
            ulong Id,
            ulong ProgramId,
            string RankTag,
            MetaWindow Window,
            MetaTarget Target
        )
        {
            this.Id = Id;
            this.ProgramId = ProgramId;
            this.RankTag = RankTag;
            this.Window = Window;
            this.Target = Target;
        }

        public MetaOp()
        {
            this.RankTag = "";
            this.Window = new();
            this.Target = new();
        }
    }
}
