// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class MetaWindow
    {
        [DataMember(Name = "kind")]
        public string Kind;
        [DataMember(Name = "value")]
        public string Value;

        public MetaWindow(
            string Kind,
            string Value
        )
        {
            this.Kind = Kind;
            this.Value = Value;
        }

        public MetaWindow()
        {
            this.Kind = "";
            this.Value = "";
        }
    }
}
