// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ProtocolSpec
    {
        [DataMember(Name = "gain")]
        public float? Gain;
        [DataMember(Name = "polarity")]
        public string? Polarity;
        [DataMember(Name = "tau_class")]
        public string? TauClass;
        [DataMember(Name = "tau_value")]
        public string? TauValue;
        [DataMember(Name = "gate")]
        public string? Gate;
        [DataMember(Name = "coupling")]
        public string? Coupling;
        [DataMember(Name = "release_pr")]
        public float? ReleasePr;

        public ProtocolSpec(
            float? Gain,
            string? Polarity,
            string? TauClass,
            string? TauValue,
            string? Gate,
            string? Coupling,
            float? ReleasePr
        )
        {
            this.Gain = Gain;
            this.Polarity = Polarity;
            this.TauClass = TauClass;
            this.TauValue = TauValue;
            this.Gate = Gate;
            this.Coupling = Coupling;
            this.ReleasePr = ReleasePr;
        }

        public ProtocolSpec()
        {
        }
    }
}
