// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class SimTick
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "sim_run_id")]
        public ulong SimRunId;
        [DataMember(Name = "tick")]
        public uint Tick;
        [DataMember(Name = "node_id")]
        public ulong NodeId;
        [DataMember(Name = "value")]
        public float Value;
        [DataMember(Name = "delta")]
        public float Delta;
        [DataMember(Name = "event")]
        public string Event;
        [DataMember(Name = "sources")]
        public System.Collections.Generic.List<ulong> Sources;

        public SimTick(
            ulong Id,
            ulong SimRunId,
            uint Tick,
            ulong NodeId,
            float Value,
            float Delta,
            string Event,
            System.Collections.Generic.List<ulong> Sources
        )
        {
            this.Id = Id;
            this.SimRunId = SimRunId;
            this.Tick = Tick;
            this.NodeId = NodeId;
            this.Value = Value;
            this.Delta = Delta;
            this.Event = Event;
            this.Sources = Sources;
        }

        public SimTick()
        {
            this.Event = "";
            this.Sources = new();
        }
    }
}
