// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class SnapshotEdge
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "snapshot_id")]
        public ulong SnapshotId;
        [DataMember(Name = "edge_id")]
        public ulong EdgeId;
        [DataMember(Name = "coeff")]
        public float Coeff;
        [DataMember(Name = "gain")]
        public float? Gain;

        public SnapshotEdge(
            ulong Id,
            ulong SnapshotId,
            ulong EdgeId,
            float Coeff,
            float? Gain
        )
        {
            this.Id = Id;
            this.SnapshotId = SnapshotId;
            this.EdgeId = EdgeId;
            this.Coeff = Coeff;
            this.Gain = Gain;
        }

        public SnapshotEdge()
        {
        }
    }
}
