// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class TensorEffect
    {
        [DataMember(Name = "code")]
        public string Code;
        [DataMember(Name = "region")]
        public string Region;
        [DataMember(Name = "action")]
        public string Action;
        [DataMember(Name = "value")]
        public float? Value;
        [DataMember(Name = "switch_to")]
        public string? SwitchTo;

        public TensorEffect(
            string Code,
            string Region,
            string Action,
            float? Value,
            string? SwitchTo
        )
        {
            this.Code = Code;
            this.Region = Region;
            this.Action = Action;
            this.Value = Value;
            this.SwitchTo = SwitchTo;
        }

        public TensorEffect()
        {
            this.Code = "";
            this.Region = "";
            this.Action = "";
        }
    }
}
